import { describe, it, expect, beforeEach, vi } from "vitest";

// Mock the global objects that GitHub Actions provides
const mockCore = {
  debug: vi.fn(),
  info: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
  setFailed: vi.fn(),
  setOutput: vi.fn(),
  summary: {
    addRaw: vi.fn().mockReturnThis(),
    write: vi.fn().mockResolvedValue(),
  },
};

const mockContext = {
  runId: 12345,
  repo: {
    owner: "testowner",
    repo: "testrepo",
  },
  payload: {
    repository: {
      html_url: "https://github.com/testowner/testrepo",
    },
  },
};

// Set up global mocks before importing the module
global.core = mockCore;
global.context = mockContext;

describe("generate_footer.cjs", () => {
  let generateFooter;

  beforeEach(async () => {
    // Reset mocks
    vi.clearAllMocks();

    // Dynamic import to get fresh module state
    const module = await import("./generate_footer.cjs");
    generateFooter = module.generateFooter;
  });

  describe("generateFooter", () => {
    it("should generate basic footer with workflow name and run URL", () => {
      const result = generateFooter(
        "Test Workflow",
        "https://github.com/test/repo/actions/runs/123",
        "",
        "",
        undefined,
        undefined,
        undefined
      );

      expect(result).toContain("> AI generated by [Test Workflow](https://github.com/test/repo/actions/runs/123)");
      expect(result).not.toContain("for #");
      expect(result).not.toContain("gh aw add");
    });

    it("should include issue number reference when provided", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", 42, undefined, undefined);

      expect(result).toContain("> AI generated by [Test Workflow](https://github.com/test/repo/actions/runs/123) for #42");
    });

    it("should include PR number reference when provided", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, 99, undefined);

      expect(result).toContain("> AI generated by [Test Workflow](https://github.com/test/repo/actions/runs/123) for #99");
    });

    it("should include discussion number reference when provided", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, undefined, 7);

      expect(result).toContain("> AI generated by [Test Workflow](https://github.com/test/repo/actions/runs/123) for discussion #7");
    });

    it("should prioritize issue number over PR number", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", 42, 99, undefined);

      expect(result).toContain("for #42");
      expect(result).not.toContain("for #99");
    });

    it("should prioritize PR number over discussion number", () => {
      const result = generateFooter("Test Workflow", "https://github.com/test/repo/actions/runs/123", "", "", undefined, 99, 7);

      expect(result).toContain("for #99");
      expect(result).not.toContain("for discussion #7");
    });

    it("should include workflow installation instructions when source is provided", () => {
      const result = generateFooter(
        "Test Workflow",
        "https://github.com/test/repo/actions/runs/123",
        "owner/repo/workflow.md@main",
        "https://github.com/owner/repo/blob/main/workflow.md",
        undefined,
        undefined,
        undefined
      );

      expect(result).toContain("gh aw add owner/repo/workflow.md@main");
      expect(result).toContain("See [usage guide](https://githubnext.github.io/gh-aw/tools/cli/)");
    });

    it("should not include installation instructions when source is empty", () => {
      const result = generateFooter(
        "Test Workflow",
        "https://github.com/test/repo/actions/runs/123",
        "",
        "",
        undefined,
        undefined,
        undefined
      );

      expect(result).not.toContain("gh aw add");
    });

    it("should include both issue reference and installation instructions", () => {
      const result = generateFooter(
        "Test Workflow",
        "https://github.com/test/repo/actions/runs/123",
        "owner/repo/workflow.md@main",
        "https://github.com/owner/repo/blob/main/workflow.md",
        42,
        undefined,
        undefined
      );

      expect(result).toContain("for #42");
      expect(result).toContain("gh aw add owner/repo/workflow.md@main");
    });

    it("should start and end with newlines", () => {
      const result = generateFooter(
        "Test Workflow",
        "https://github.com/test/repo/actions/runs/123",
        "",
        "",
        undefined,
        undefined,
        undefined
      );

      expect(result).toMatch(/^\n\n/);
      expect(result).toMatch(/\n$/);
    });

    it("should handle special characters in workflow name", () => {
      const result = generateFooter(
        "Test Workflow (v2) [beta]",
        "https://github.com/test/repo/actions/runs/123",
        "",
        "",
        undefined,
        undefined,
        undefined
      );

      expect(result).toContain("> AI generated by [Test Workflow (v2) [beta]](https://github.com/test/repo/actions/runs/123)");
    });
  });
});
