// Network permissions hook generator for Claude Code engine
// Generates a Python hook script for network permissions validation

const fs = require('fs');
const path = require('path');

async function main() {
  try {
    // Get the allowed domains from environment variable
    const allowedDomainsEnv = process.env.GITHUB_AW_ALLOWED_DOMAINS;
    if (!allowedDomainsEnv) {
      core.error('GITHUB_AW_ALLOWED_DOMAINS environment variable not set');
      throw new Error('Missing required environment variable GITHUB_AW_ALLOWED_DOMAINS');
    }

    // Parse the allowed domains JSON
    let allowedDomains;
    try {
      allowedDomains = JSON.parse(allowedDomainsEnv);
    } catch (error) {
      core.error(`Failed to parse allowed domains JSON: ${error.message}`);
      throw error;
    }

    console.log(`Generating network permissions hook with ${allowedDomains.length} allowed domains`);

    // Generate the Python hook script content
    const pythonScript = generatePythonHookScript(allowedDomains);

    // Create the .claude/hooks directory
    const hooksDir = '.claude/hooks';
    await io.mkdirP(hooksDir);
    console.log(`Created directory: ${hooksDir}`);

    // Write the Python hook script
    const hookPath = path.join(hooksDir, 'network_permissions.py');
    fs.writeFileSync(hookPath, pythonScript, 'utf8');
    console.log(`Generated network permissions hook: ${hookPath}`);

    // Make the script executable
    fs.chmodSync(hookPath, '755');
    console.log(`Set executable permissions on: ${hookPath}`);

    console.log('✓ Network permissions hook generated successfully');
    
  } catch (error) {
    core.error(`Failed to generate network permissions hook: ${error.message}`);
    throw error;
  }
}

function generatePythonHookScript(allowedDomains) {
  // Convert domain list to JSON for embedding in Python
  const domainsJSON = JSON.stringify(allowedDomains);

  return `#!/usr/bin/env python3
"""
Network permissions validator for Claude Code engine.
Generated by gh-aw from engine network permissions configuration.
"""

import json
import sys
import urllib.parse
import re

# Domain allow-list (populated during generation)
ALLOWED_DOMAINS = ${domainsJSON}

def extract_domain(url_or_query):
    """Extract domain from URL or search query."""
    if not url_or_query:
        return None
    
    if url_or_query.startswith(('http://', 'https://')):
        return urllib.parse.urlparse(url_or_query).netloc.lower()
    
    # Check for domain patterns in search queries
    match = re.search(r'site:([a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})', url_or_query)
    if match:
        return match.group(1).lower()
    
    return None

def is_domain_allowed(domain):
    """Check if domain is allowed."""
    if not domain:
        # If no domain detected, allow only if not under deny-all policy
        return bool(ALLOWED_DOMAINS)  # False if empty list (deny-all), True if has domains
    
    # Empty allowed domains means deny all
    if not ALLOWED_DOMAINS:
        return False
    
    for pattern in ALLOWED_DOMAINS:
        regex = pattern.replace('.', r'\\.').replace('*', '.*')
        if re.match(f'^{regex}$', domain):
            return True
    return False

# Main logic
try:
    data = json.load(sys.stdin)
    tool_name = data.get('tool_name', '')
    tool_input = data.get('tool_input', {})
    
    if tool_name not in ['WebFetch', 'WebSearch']:
        sys.exit(0)  # Allow other tools
    
    target = tool_input.get('url') or tool_input.get('query', '')
    domain = extract_domain(target)
    
    # For WebSearch, apply domain restrictions consistently
    # If no domain detected in search query, check if restrictions are in place
    if tool_name == 'WebSearch' and not domain:
        # Since this hook is only generated when network permissions are configured,
        # empty ALLOWED_DOMAINS means deny-all policy
        if not ALLOWED_DOMAINS:  # Empty list means deny all
            print(f"Network access blocked: deny-all policy in effect", file=sys.stderr)
            print(f"No domains are allowed for WebSearch", file=sys.stderr)
            sys.exit(2)  # Block under deny-all policy
        else:
            print(f"Network access blocked for web-search: no specific domain detected", file=sys.stderr)
            print(f"Allowed domains: {', '.join(ALLOWED_DOMAINS)}", file=sys.stderr)
            sys.exit(2)  # Block general searches when domain allowlist is configured
    
    if not is_domain_allowed(domain):
        print(f"Network access blocked for domain: {domain}", file=sys.stderr)
        print(f"Allowed domains: {', '.join(ALLOWED_DOMAINS)}", file=sys.stderr)
        sys.exit(2)  # Block with feedback to Claude
    
    sys.exit(0)  # Allow
    
except Exception as e:
    print(f"Network validation error: {e}", file=sys.stderr)
    sys.exit(2)  # Block on errors
`;
}

await main();