/**
 * Network permissions validator for Claude Code engine using actions/github-script.
 * Generated by gh-aw from engine network permissions configuration.
 *
 * This script validates network access requests against an allow-list of domains.
 * It checks WebFetch and WebSearch tool requests and blocks unauthorized domains.
 */

/**
 * Extract domain from URL or search query
 * @param {string} urlOrQuery - The URL or search query to extract domain from
 * @returns {string|null} The extracted domain or null if none found
 */
function extractDomain(urlOrQuery) {
  if (!urlOrQuery || typeof urlOrQuery !== "string") {
    return null;
  }

  // Handle direct URLs (case insensitive)
  const lowerUrlOrQuery = urlOrQuery.toLowerCase();
  if (
    lowerUrlOrQuery.startsWith("http://") ||
    lowerUrlOrQuery.startsWith("https://")
  ) {
    try {
      const url = new URL(urlOrQuery);
      // Return null for URLs without valid hostnames
      if (!url.hostname || url.hostname === "") {
        return null;
      }
      return url.hostname.toLowerCase();
    } catch (e) {
      return null;
    }
  }

  // Check for domain patterns in search queries (site:domain.com)
  const siteMatch = urlOrQuery.match(/site:([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/i);
  if (siteMatch) {
    return siteMatch[1].toLowerCase();
  }

  return null;
}

/**
 * Check if domain is allowed based on the allow-list patterns
 * @param {string} domain - Domain to check
 * @param {string[]} allowedDomains - Array of allowed domain patterns
 * @returns {boolean} True if domain is allowed, false otherwise
 */
function isDomainAllowed(domain, allowedDomains) {
  if (!domain) {
    // If no domain detected, allow only if not under deny-all policy
    return allowedDomains.length > 0;
  }

  // Empty allowed domains means deny all
  if (allowedDomains.length === 0) {
    return false;
  }

  // Normalize domain to lowercase for case-insensitive comparison
  const normalizedDomain = domain.toLowerCase();

  // Check against each allowed pattern
  for (const pattern of allowedDomains) {
    // Normalize pattern to lowercase for case-insensitive comparison
    const normalizedPattern = pattern.toLowerCase();

    // Convert wildcard pattern to regex
    const regexPattern = normalizedPattern
      .replace(/\./g, "\\.") // Escape dots
      .replace(/\*/g, ".*"); // Convert * to .*

    const regex = new RegExp(`^${regexPattern}$`);
    if (regex.test(normalizedDomain)) {
      return true;
    }
  }

  return false;
}

/**
 * Main validation function
 */
async function main() {
  try {
    // Get allowed domains from environment variable
    const allowedDomainsEnv = process.env.GITHUB_AW_NETWORK_DOMAINS;
    let allowedDomains = [];

    if (allowedDomainsEnv) {
      try {
        allowedDomains = JSON.parse(allowedDomainsEnv);
        if (!Array.isArray(allowedDomains)) {
          allowedDomains = [];
        }
      } catch (e) {
        core.error(`Failed to parse GITHUB_AW_NETWORK_DOMAINS: ${e.message}`);
        allowedDomains = [];
      }
    }

    // Get tool input from environment - actions/github-script provides these via inputs
    const toolName = process.env.GITHUB_AW_TOOL_NAME || "";
    const toolInputEnv = process.env.GITHUB_AW_TOOL_INPUT;
    let toolInput = {};

    if (toolInputEnv) {
      try {
        toolInput = JSON.parse(toolInputEnv);
      } catch (e) {
        core.error(`Failed to parse GITHUB_AW_TOOL_INPUT: ${e.message}`);
        toolInput = {};
      }
    }

    // Only validate WebFetch and WebSearch tools
    if (toolName !== "WebFetch" && toolName !== "WebSearch") {
      console.log(`Tool ${toolName} is not subject to network restrictions`);
      return; // Allow other tools
    }

    // Extract target URL or query
    const target = toolInput.url || toolInput.query || "";
    const domain = extractDomain(target);

    console.log(`Validating ${toolName} request for target: ${target}`);
    console.log(`Extracted domain: ${domain || "none"}`);
    console.log(`Allowed domains: ${JSON.stringify(allowedDomains)}`);

    // Special handling for WebSearch without specific domain
    if (toolName === "WebSearch" && !domain) {
      if (allowedDomains.length === 0) {
        // Deny-all policy
        core.setFailed(
          "Network access blocked: deny-all policy in effect. No domains are allowed for WebSearch"
        );
        return;
      } else {
        // Domain allowlist configured - block general searches
        core.setFailed(
          `Network access blocked for web-search: no specific domain detected. Allowed domains: ${allowedDomains.join(", ")}`
        );
        return;
      }
    }

    // Check if domain is allowed
    if (!isDomainAllowed(domain, allowedDomains)) {
      const message = `Network access blocked for domain: ${domain}. Allowed domains: ${allowedDomains.join(", ")}`;
      core.setFailed(message);
      return;
    }

    console.log(`Network access allowed for domain: ${domain}`);
  } catch (error) {
    const message = `Network validation error: ${error.message}`;
    core.error(message);
    core.setFailed(message);
  }
}

// Execute main function
await main();
