// @ts-check
/// <reference types="@actions/github-script" />

const {
  runUpdateWorkflow,
  createRenderStagedItem,
  createGetSummaryLine,
  createContextValidator,
  createNumberExtractor,
} = require("./update_runner.cjs");

// Create context validator for pull requests
const isPRContext = createContextValidator({
  eventNames: ["pull_request", "pull_request_review", "pull_request_review_comment", "pull_request_target"],
  checkIssueCommentOnPR: true,
});

// Create number extractor for pull requests
const getPRNumber = createNumberExtractor({
  payloadPaths: ["pull_request.number", "issue.number"],
});

// Use shared helper for staged preview rendering
const renderStagedItem = createRenderStagedItem({
  entityName: "Pull Request",
  numberField: "pull_request_number",
  targetLabel: "Target PR:",
  currentTargetText: "Current pull request",
  includeOperation: true,
});

/**
 * Execute the pull request update API call
 * @param {any} github - GitHub API client
 * @param {any} context - GitHub Actions context
 * @param {number} prNumber - PR number to update
 * @param {any} updateData - Data to update
 * @returns {Promise<any>} Updated pull request
 */
async function executePRUpdate(github, context, prNumber, updateData) {
  // Handle body operation (append/prepend/replace)
  const operation = updateData._operation || "replace";
  const rawBody = updateData._rawBody;

  // Remove internal fields
  const { _operation, _rawBody, ...apiData } = updateData;

  // If we have a body with append/prepend operation, handle it
  if (rawBody !== undefined && (operation === "append" || operation === "prepend")) {
    // Fetch current PR body
    const { data: currentPR } = await github.rest.pulls.get({
      owner: context.repo.owner,
      repo: context.repo.repo,
      pull_number: prNumber,
    });
    const currentBody = currentPR.body || "";

    // Get workflow run URL for AI attribution
    const workflowName = process.env.GH_AW_WORKFLOW_NAME || "GitHub Agentic Workflow";
    const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

    // Build the AI footer
    const aiFooter = `\n\n> AI generated by [${workflowName}](${runUrl})`;

    if (operation === "prepend") {
      // Prepend: add content, AI footer, and horizontal line at the start
      const prependSection = `${rawBody}${aiFooter}\n\n---\n\n`;
      apiData.body = prependSection + currentBody;
      core.info("Operation: prepend (add to start with separator)");
    } else {
      // Append: add horizontal line, content, and AI footer at the end
      const appendSection = `\n\n---\n\n${rawBody}${aiFooter}`;
      apiData.body = currentBody + appendSection;
      core.info("Operation: append (add to end with separator)");
    }
    core.info(`Will update body (length: ${apiData.body.length})`);
  } else if (rawBody !== undefined) {
    // Replace: just use the new content as-is (already in apiData.body)
    core.info("Operation: replace (full body replacement)");
  }

  const { data: pr } = await github.rest.pulls.update({
    owner: context.repo.owner,
    repo: context.repo.repo,
    pull_number: prNumber,
    ...apiData,
  });

  return pr;
}

// Use shared helper for summary line generation
const getSummaryLine = createGetSummaryLine({
  entityPrefix: "PR",
});

async function main() {
  return await runUpdateWorkflow({
    itemType: "update_pull_request",
    displayName: "pull request",
    displayNamePlural: "pull requests",
    numberField: "pull_request_number",
    outputNumberKey: "pull_request_number",
    outputUrlKey: "pull_request_url",
    isValidContext: isPRContext,
    getContextNumber: getPRNumber,
    supportsStatus: false,
    supportsOperation: true,
    renderStagedItem,
    executeUpdate: executePRUpdate,
    getSummaryLine,
  });
}

await main();
