// @ts-check
/// <reference types="@actions/github-script" />

const { runUpdateWorkflow } = require("./update_runner.cjs");

/**
 * Check if the current context is a valid pull request context
 * @param {string} eventName - GitHub event name
 * @param {any} payload - GitHub event payload
 * @returns {boolean} Whether context is valid for PR updates
 */
function isPRContext(eventName, payload) {
  const isPR =
    eventName === "pull_request" ||
    eventName === "pull_request_review" ||
    eventName === "pull_request_review_comment" ||
    eventName === "pull_request_target";

  // Also check for issue_comment on a PR
  const isIssueCommentOnPR = eventName === "issue_comment" && payload.issue && payload.issue.pull_request;

  return isPR || isIssueCommentOnPR;
}

/**
 * Get pull request number from the context payload
 * @param {any} payload - GitHub event payload
 * @returns {number|undefined} PR number or undefined
 */
function getPRNumber(payload) {
  if (payload.pull_request) {
    return payload.pull_request.number;
  }
  // For issue_comment events on PRs, the PR number is in issue.number
  if (payload.issue && payload.issue.pull_request) {
    return payload.issue.number;
  }
  return undefined;
}

/**
 * Render a staged preview item for PR updates
 * @param {any} item - Update item
 * @param {number} index - Item index (0-based)
 * @returns {string} Markdown content for the preview
 */
function renderStagedItem(item, index) {
  let content = `### Pull Request Update ${index + 1}\n`;
  if (item.pull_request_number) {
    content += `**Target PR:** #${item.pull_request_number}\n\n`;
  } else {
    content += `**Target:** Current pull request\n\n`;
  }

  if (item.title !== undefined) {
    content += `**New Title:** ${item.title}\n\n`;
  }
  if (item.body !== undefined) {
    const operation = item.operation || "append";
    content += `**Operation:** ${operation}\n`;
    content += `**Body Content:**\n${item.body}\n\n`;
  }
  return content;
}

/**
 * Execute the pull request update API call
 * @param {any} github - GitHub API client
 * @param {any} context - GitHub Actions context
 * @param {number} prNumber - PR number to update
 * @param {any} updateData - Data to update
 * @returns {Promise<any>} Updated pull request
 */
async function executePRUpdate(github, context, prNumber, updateData) {
  // Handle body operation (append/prepend/replace)
  const operation = updateData._operation || "replace";
  const rawBody = updateData._rawBody;

  // Remove internal fields
  const { _operation, _rawBody, ...apiData } = updateData;

  // If we have a body with append/prepend operation, handle it
  if (rawBody !== undefined && (operation === "append" || operation === "prepend")) {
    // Fetch current PR body
    const { data: currentPR } = await github.rest.pulls.get({
      owner: context.repo.owner,
      repo: context.repo.repo,
      pull_number: prNumber,
    });
    const currentBody = currentPR.body || "";

    // Get workflow run URL for AI attribution
    const workflowName = process.env.GH_AW_WORKFLOW_NAME || "GitHub Agentic Workflow";
    const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

    // Build the AI footer
    const aiFooter = `\n\n> AI generated by [${workflowName}](${runUrl})`;

    if (operation === "prepend") {
      // Prepend: add content, AI footer, and horizontal line at the start
      const prependSection = `${rawBody}${aiFooter}\n\n---\n\n`;
      apiData.body = prependSection + currentBody;
      core.info("Operation: prepend (add to start with separator)");
    } else {
      // Append: add horizontal line, content, and AI footer at the end
      const appendSection = `\n\n---\n\n${rawBody}${aiFooter}`;
      apiData.body = currentBody + appendSection;
      core.info("Operation: append (add to end with separator)");
    }
    core.info(`Will update body (length: ${apiData.body.length})`);
  } else if (rawBody !== undefined) {
    // Replace: just use the new content as-is (already in apiData.body)
    core.info("Operation: replace (full body replacement)");
  }

  const { data: pr } = await github.rest.pulls.update({
    owner: context.repo.owner,
    repo: context.repo.repo,
    pull_number: prNumber,
    ...apiData,
  });

  return pr;
}

/**
 * Generate summary line for an updated PR
 * @param {any} pr - Updated pull request
 * @returns {string} Markdown summary line
 */
function getSummaryLine(pr) {
  return `- PR #${pr.number}: [${pr.title}](${pr.html_url})\n`;
}

async function main() {
  return await runUpdateWorkflow({
    itemType: "update_pull_request",
    displayName: "pull request",
    displayNamePlural: "pull requests",
    numberField: "pull_request_number",
    outputNumberKey: "pull_request_number",
    outputUrlKey: "pull_request_url",
    isValidContext: isPRContext,
    getContextNumber: getPRNumber,
    supportsStatus: false,
    supportsOperation: true,
    renderStagedItem,
    executeUpdate: executePRUpdate,
    getSummaryLine,
  });
}

await main();
