# GitHub Agentic Workflows Catalog
#
# This file provides a searchable catalog of available workflows organized by category.
# It enables deterministic workflow discovery for campaign creation and optimization.
#
# Usage:
#   - Campaign generators query this catalog to find matching workflows
#   - Categories help match workflows to campaign goals
#   - Keywords enable fuzzy search across workflow purposes
#
# Maintenance:
#   - Update this file when adding new workflows
#   - Keep descriptions synchronized with workflow frontmatter
#   - Add new categories as workflow types evolve

version: "1.0"
last_updated: "2026-01-09"

categories:
  security:
    description: "Security analysis, vulnerability scanning, and remediation workflows"
    keywords:
      - security
      - vulnerability
      - cve
      - scan
      - malicious
      - secrets
    workflows:
      - id: daily-malicious-code-scan
        description: "Daily scan for potentially malicious code patterns and security vulnerabilities"
        safe_outputs:
          - create-issue
          - add-comment
      
      # Add more security workflows as they are created

  dependency:
    description: "Dependency management, updates, and version tracking workflows"
    keywords:
      - dependency
      - upgrade
      - update
      - version
      - npm
      - go
      - python
    workflows:
      - id: cli-version-checker
        description: "Monitors and updates agentic CLI tools for new versions"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      # Add more dependency workflows as they are created

  documentation:
    description: "Documentation creation, maintenance, and quality assurance workflows"
    keywords:
      - doc
      - documentation
      - guide
      - readme
      - glossary
      - blog
    workflows:
      - id: glossary-maintainer
        description: "Maintains and updates project glossary and terminology"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      - id: blog-auditor
        description: "Verifies blog page accessibility and content quality"
        safe_outputs:
          - create-issue
          - add-comment
      
      # Add more documentation workflows as they are created

  quality:
    description: "Code quality, refactoring, and technical debt management workflows"
    keywords:
      - quality
      - lint
      - refactor
      - clean
      - metrics
      - analysis
    workflows:
      - id: daily-code-metrics
        description: "Tracks and visualizes daily code metrics and trends"
        safe_outputs:
          - create-discussion
          - add-comment
      
      - id: semantic-function-refactor
        description: "Identifies and refactors functions for improved code quality"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      - id: breaking-change-checker
        description: "Daily analysis of recent commits for breaking CLI changes"
        safe_outputs:
          - create-issue
          - add-comment
      
      # Add more quality workflows as they are created

  ci-cd:
    description: "CI/CD optimization, monitoring, and troubleshooting workflows"
    keywords:
      - ci
      - cd
      - build
      - test
      - workflow
      - actions
      - performance
    workflows:
      - id: ci-doctor
        description: "Investigates failed CI workflows to identify root causes"
        safe_outputs:
          - create-issue
          - add-comment
      
      - id: ci-coach
        description: "Daily CI optimization analysis for efficiency improvements"
        safe_outputs:
          - create-discussion
          - add-comment
      
      - id: audit-workflows
        description: "Daily audit of agentic workflow runs to identify issues"
        safe_outputs:
          - create-issue
          - add-comment
      
      - id: daily-cli-performance
        description: "Runs benchmarks and tracks CLI performance trends"
        safe_outputs:
          - create-discussion
          - add-comment
      
      # Add more CI/CD workflows as they are created

  analytics:
    description: "Analysis, reporting, and insights workflows"
    keywords:
      - analysis
      - report
      - insights
      - metrics
      - tracking
      - statistics
    workflows:
      - id: copilot-agent-analysis
        description: "Analyzes GitHub Copilot agent usage patterns in pull requests"
        safe_outputs:
          - create-discussion
          - add-comment
      
      - id: copilot-session-insights
        description: "Analyzes GitHub Copilot agent sessions for usage patterns"
        safe_outputs:
          - create-discussion
          - add-comment
      
      - id: daily-code-metrics
        description: "Tracks and visualizes daily code metrics and trends"
        safe_outputs:
          - create-discussion
          - add-comment
      
      - id: commit-changes-analyzer
        description: "Analyzes and reports all changes since a specified commit"
        safe_outputs:
          - add-comment
      
      # Add more analytics workflows as they are created

  automation:
    description: "General automation, maintenance, and optimization workflows"
    keywords:
      - automation
      - maintenance
      - optimization
      - cleanup
      - daily
    workflows:
      - id: daily-file-diet
        description: "Analyzes and optimizes file sizes across the repository"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      - id: changeset
        description: "Automatically creates changeset files for release notes"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      # Add more automation workflows as they are created

  meta-orchestration:
    description: "Campaign management and high-level orchestration workflows"
    keywords:
      - campaign
      - orchestration
      - coordination
      - meta
      - management
    workflows:
      - id: campaign-generator
        description: "Campaign generator that creates and assigns campaign design tasks"
        safe_outputs:
          - add-comment
          - create-project
          - assign-to-agent
      
      - id: agent-performance-analyzer
        description: "Meta-orchestrator analyzing AI agent performance and effectiveness"
        safe_outputs:
          - create-discussion
          - add-comment
      
      # Add more meta-orchestration workflows as they are created

  tools:
    description: "Developer tools, utilities, and helper workflows"
    keywords:
      - tool
      - utility
      - helper
      - generator
      - command
    workflows:
      - id: craft
        description: "Generates new agentic workflow markdown files from user requests"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      - id: workflow-generator
        description: "Creates workflow files based on specifications"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      - id: archie
        description: "Generates Mermaid diagrams visualizing issue/PR relationships"
        safe_outputs:
          - add-comment
      
      - id: brave
        description: "Performs web searches using Brave search engine"
        safe_outputs:
          - add-comment
      
      # Add more tool workflows as they are created

  testing:
    description: "Testing, validation, and quality assurance workflows"
    keywords:
      - test
      - testing
      - validation
      - smoke
      - qa
    workflows:
      - id: daily-choice-test
        description: "Daily test workflow using Claude with custom safe-output job"
        safe_outputs:
          - add-comment
      
      - id: daily-multi-device-docs-tester
        description: "Tests documentation across multiple devices and browsers"
        safe_outputs:
          - create-issue
          - add-comment
      
      - id: smoke-claude
        description: "Smoke tests for Claude engine integration"
        safe_outputs:
          - add-comment
      
      # Add more testing workflows as they are created

# Maintenance Notes:
# - This catalog should be updated whenever new workflows are added
# - Keep workflow IDs synchronized with actual .md filenames (without extension)
# - Categories can be extended as new workflow types emerge
# - Keywords should be lowercase and cover common search terms
# - Safe outputs help campaign designers understand workflow capabilities
