# GitHub Agentic Workflows Catalog
#
# ⚠️ DEPRECATED: This static catalog is no longer used for workflow discovery.
#
# As of 2026-01-10, the campaign generator now uses fully dynamic discovery:
# - Agentic workflows: Scanned from .github/workflows/*.md with frontmatter parsing
# - Regular workflows: Scanned from .github/workflows/*.yml (excluding .lock.yml)
# - External collections: Referenced from known sources (e.g., agentics collection)
#
# This file is kept for historical reference and may be removed in a future version.
# No maintenance required - workflow discovery is now automatic.
#
# Previous purpose:
#   - Provided a searchable catalog of workflows organized by category
#   - Enabled deterministic workflow discovery for campaign creation
#
# New approach benefits:
#   - Always up-to-date without manual maintenance
#   - Discovers all workflows automatically
#   - Reads actual workflow definitions rather than static metadata

version: "1.0"
last_updated: "2026-01-09"
deprecated: true
deprecated_date: "2026-01-10"
replacement: "Dynamic filesystem scanning with frontmatter parsing"

categories:
  security:
    description: "Security analysis, vulnerability scanning, and remediation workflows"
    keywords:
      - security
      - vulnerability
      - cve
      - scan
      - malicious
      - secrets
    workflows:
      - id: daily-malicious-code-scan
        description: "Daily scan for potentially malicious code patterns and security vulnerabilities"
        safe_outputs:
          - create-issue
          - add-comment
      
      # Add more security workflows as they are created

  dependency:
    description: "Dependency management, updates, and version tracking workflows"
    keywords:
      - dependency
      - upgrade
      - update
      - version
      - npm
      - go
      - python
    workflows:
      - id: cli-version-checker
        description: "Monitors and updates agentic CLI tools for new versions"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      # Add more dependency workflows as they are created

  documentation:
    description: "Documentation creation, maintenance, and quality assurance workflows"
    keywords:
      - doc
      - documentation
      - guide
      - readme
      - glossary
      - blog
    workflows:
      - id: glossary-maintainer
        description: "Maintains and updates project glossary and terminology"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      - id: blog-auditor
        description: "Verifies blog page accessibility and content quality"
        safe_outputs:
          - create-issue
          - add-comment
      
      # Add more documentation workflows as they are created

  quality:
    description: "Code quality, refactoring, and technical debt management workflows"
    keywords:
      - quality
      - lint
      - refactor
      - clean
      - metrics
      - analysis
    workflows:
      - id: daily-code-metrics
        description: "Tracks and visualizes daily code metrics and trends"
        safe_outputs:
          - create-discussion
          - add-comment
      
      - id: semantic-function-refactor
        description: "Identifies and refactors functions for improved code quality"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      - id: breaking-change-checker
        description: "Daily analysis of recent commits for breaking CLI changes"
        safe_outputs:
          - create-issue
          - add-comment
      
      # Add more quality workflows as they are created

  ci-cd:
    description: "CI/CD optimization, monitoring, and troubleshooting workflows"
    keywords:
      - ci
      - cd
      - build
      - test
      - workflow
      - actions
      - performance
    workflows:
      - id: ci-doctor
        description: "Investigates failed CI workflows to identify root causes"
        safe_outputs:
          - create-issue
          - add-comment
      
      - id: ci-coach
        description: "Daily CI optimization analysis for efficiency improvements"
        safe_outputs:
          - create-discussion
          - add-comment
      
      - id: audit-workflows
        description: "Daily audit of agentic workflow runs to identify issues"
        safe_outputs:
          - create-issue
          - add-comment
      
      - id: daily-cli-performance
        description: "Runs benchmarks and tracks CLI performance trends"
        safe_outputs:
          - create-discussion
          - add-comment
      
      # Add more CI/CD workflows as they are created

  analytics:
    description: "Analysis, reporting, and insights workflows"
    keywords:
      - analysis
      - report
      - insights
      - metrics
      - tracking
      - statistics
    workflows:
      - id: copilot-agent-analysis
        description: "Analyzes GitHub Copilot agent usage patterns in pull requests"
        safe_outputs:
          - create-discussion
          - add-comment
      
      - id: copilot-session-insights
        description: "Analyzes GitHub Copilot agent sessions for usage patterns"
        safe_outputs:
          - create-discussion
          - add-comment
      
      - id: daily-code-metrics
        description: "Tracks and visualizes daily code metrics and trends"
        safe_outputs:
          - create-discussion
          - add-comment
      
      - id: commit-changes-analyzer
        description: "Analyzes and reports all changes since a specified commit"
        safe_outputs:
          - add-comment
      
      # Add more analytics workflows as they are created

  automation:
    description: "General automation, maintenance, and optimization workflows"
    keywords:
      - automation
      - maintenance
      - optimization
      - cleanup
      - daily
    workflows:
      - id: daily-file-diet
        description: "Analyzes and optimizes file sizes across the repository"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      - id: changeset
        description: "Automatically creates changeset files for release notes"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      # Add more automation workflows as they are created

  meta-orchestration:
    description: "Campaign management and high-level orchestration workflows"
    keywords:
      - campaign
      - orchestration
      - coordination
      - meta
      - management
    workflows:
      - id: campaign-generator
        description: "Campaign generator that creates and assigns campaign design tasks"
        safe_outputs:
          - add-comment
          - create-project
          - assign-to-agent
      
      - id: agent-performance-analyzer
        description: "Meta-orchestrator analyzing AI agent performance and effectiveness"
        safe_outputs:
          - create-discussion
          - add-comment
      
      # Add more meta-orchestration workflows as they are created

  tools:
    description: "Developer tools, utilities, and helper workflows"
    keywords:
      - tool
      - utility
      - helper
      - generator
      - command
    workflows:
      - id: craft
        description: "Generates new agentic workflow markdown files from user requests"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      - id: workflow-generator
        description: "Creates workflow files based on specifications"
        safe_outputs:
          - create-pull-request
          - add-comment
      
      - id: archie
        description: "Generates Mermaid diagrams visualizing issue/PR relationships"
        safe_outputs:
          - add-comment
      
      - id: brave
        description: "Performs web searches using Brave search engine"
        safe_outputs:
          - add-comment
      
      # Add more tool workflows as they are created

  testing:
    description: "Testing, validation, and quality assurance workflows"
    keywords:
      - test
      - testing
      - validation
      - smoke
      - qa
    workflows:
      - id: daily-choice-test
        description: "Daily test workflow using Claude with custom safe-output job"
        safe_outputs:
          - add-comment
      
      - id: daily-multi-device-docs-tester
        description: "Tests documentation across multiple devices and browsers"
        safe_outputs:
          - create-issue
          - add-comment
      
      - id: smoke-claude
        description: "Smoke tests for Claude engine integration"
        safe_outputs:
          - add-comment
      
      # Add more testing workflows as they are created

# Maintenance Notes:
# - This catalog should be updated whenever new workflows are added
# - Keep workflow IDs synchronized with actual .md filenames (without extension)
# - Categories can be extended as new workflow types emerge
# - Keywords should be lowercase and cover common search terms
# - Safe outputs help campaign designers understand workflow capabilities

# External Workflow Collections:
# Workflows can also be sourced from external collections like the "agentics" collection
# at https://github.com/githubnext/agentics. When suggesting workflows for campaigns,
# consider both this repository's workflows and workflows from the agentics collection.

external_collections:
  agentics:
    url: https://github.com/githubnext/agentics
    description: "A sample family of reusable GitHub Agentic Workflows"
    categories:
      triage_analysis:
        description: "Depth triage and analysis workflows"
        workflows:
          - id: issue-triage
            name: "Issue Triage"
            description: "Triage issues and pull requests"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/issue-triage.md
          
          - id: ci-doctor
            name: "CI Doctor"
            description: "Monitor CI workflows and investigate failures automatically"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/ci-doctor.md
          
          - id: repo-ask
            name: "Repo Ask"
            description: "Intelligent research assistant for repository questions and analysis"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/repo-ask.md
          
          - id: daily-accessibility-review
            name: "Daily Accessibility Review"
            description: "Review application accessibility by automatically running and using the application"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/daily-accessibility-review.md
          
          - id: q-workflow-optimizer
            name: "Q - Workflow Optimizer"
            description: "Expert system that analyzes and optimizes agentic workflows"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/q.md
      
      research_planning:
        description: "Research, status, and planning workflows"
        workflows:
          - id: weekly-research
            name: "Weekly Research"
            description: "Collect research updates and industry trends"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/weekly-research.md
          
          - id: daily-team-status
            name: "Daily Team Status"
            description: "Assess repository activity and create status reports"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/daily-team-status.md
          
          - id: daily-plan
            name: "Daily Plan"
            description: "Update planning issues for team coordination"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/daily-plan.md
          
          - id: plan-command
            name: "Plan Command"
            description: "Break down issues into actionable sub-tasks with /plan command"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/plan.md
      
      coding_development:
        description: "Coding and development workflows"
        workflows:
          - id: daily-progress
            name: "Daily Progress"
            description: "Automated daily feature development following a structured roadmap"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/daily-progress.md
          
          - id: daily-dependency-updater
            name: "Daily Dependency Updater"
            description: "Update dependencies and create pull requests"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/daily-dependency-updates.md
          
          - id: update-docs
            name: "Regular Documentation Update"
            description: "Update documentation automatically"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/update-docs.md
          
          - id: pr-fix
            name: "PR Fix"
            description: "Analyze failing CI checks and implement fixes for pull requests"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/pr-fix.md
          
          - id: daily-adhoc-qa
            name: "Daily Adhoc QA"
            description: "Perform adhoc explorative quality assurance tasks"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/daily-qa.md
          
          - id: daily-test-coverage-improver
            name: "Daily Test Coverage Improver"
            description: "Improve test coverage by adding meaningful tests to under-tested areas"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/daily-test-improver.md
          
          - id: daily-performance-improver
            name: "Daily Performance Improver"
            description: "Analyze and improve code performance through benchmarking and optimization"
            docs_url: https://github.com/githubnext/agentics/blob/main/docs/daily-perf-improver.md
