// @ts-check
import { describe, it, expect, beforeEach, vi } from "vitest";

// Mock core and context globals
const mockCore = {
  info: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
  summary: {
    addRaw: vi.fn().mockReturnThis(),
    write: vi.fn(),
  },
};

const mockContext = {
  repo: {
    owner: "testowner",
    repo: "testrepo",
  },
};

global.core = mockCore;
global.context = mockContext;

describe("close_expired_discussions", () => {
  let mockGithub;

  beforeEach(() => {
    vi.clearAllMocks();
    mockGithub = {
      graphql: vi.fn(),
    };
    global.github = mockGithub;
  });

  describe("hasExpirationComment", () => {
    it("should return true when expiration comment exists", async () => {
      // Mock the import after globals are set
      const module = await import("./close_expired_discussions.cjs");

      // Mock GraphQL response with existing expiration comment
      mockGithub.graphql.mockResolvedValueOnce({
        node: {
          comments: {
            nodes: [{ body: "Some other comment" }, { body: "This discussion was automatically closed because it expired on 2026-01-20T09:20:00.000Z.\n\n<!-- gh-aw-closed -->" }, { body: "Another comment" }],
          },
        },
      });

      // Access the function through module exports for testing
      // Note: hasExpirationComment is not exported, so we test it indirectly through main()
      // For now, we'll test the integration in the main() function tests below
      expect(mockGithub.graphql).toBeDefined();
    });

    it("should return false when no expiration comment exists", async () => {
      mockGithub.graphql.mockResolvedValueOnce({
        node: {
          comments: {
            nodes: [{ body: "Some regular comment" }, { body: "Another regular comment" }],
          },
        },
      });

      expect(mockGithub.graphql).toBeDefined();
    });
  });

  describe("main - duplicate comment prevention", () => {
    it("should skip adding comment if one already exists", async () => {
      const module = await import("./close_expired_discussions.cjs");

      // Mock the search query to return an open discussion with expiration marker
      mockGithub.graphql
        // First call: searchDiscussionsWithExpiration
        .mockResolvedValueOnce({
          repository: {
            discussions: {
              pageInfo: {
                hasNextPage: false,
                endCursor: null,
              },
              nodes: [
                {
                  id: "D_test123",
                  number: 11057,
                  title: "Test Discussion",
                  url: "https://github.com/testowner/testrepo/discussions/11057",
                  body: "> AI generated by Test Workflow\n>\n> - [x] expires <!-- gh-aw-expires: 2020-01-20T09:20:00.000Z --> on Jan 20, 2020, 9:20 AM UTC",
                  createdAt: "2020-01-19T09:20:00.000Z",
                },
              ],
            },
          },
        })
        // Second call: hasExpirationComment - returns true (comment exists)
        .mockResolvedValueOnce({
          node: {
            comments: {
              nodes: [{ body: "This discussion was automatically closed because it expired on 2020-01-20T09:20:00.000Z.\n\n<!-- gh-aw-closed -->" }],
            },
          },
        })
        // Third call: closeDiscussionAsOutdated
        .mockResolvedValueOnce({
          closeDiscussion: {
            discussion: {
              id: "D_test123",
              url: "https://github.com/testowner/testrepo/discussions/11057",
            },
          },
        });

      await module.main();

      // Verify that the comment was NOT added (only 3 graphql calls, not 4)
      expect(mockGithub.graphql).toHaveBeenCalledTimes(3);

      // Verify that we checked for existing comments
      expect(mockCore.warning).toHaveBeenCalledWith(expect.stringContaining("already has an expiration comment"));

      // Verify that we still tried to close the discussion
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("Attempting to close discussion"));
    });

    it("should add comment if none exists", async () => {
      const module = await import("./close_expired_discussions.cjs");

      // Mock the search query to return an open discussion with expiration marker
      mockGithub.graphql
        // First call: searchDiscussionsWithExpiration
        .mockResolvedValueOnce({
          repository: {
            discussions: {
              pageInfo: {
                hasNextPage: false,
                endCursor: null,
              },
              nodes: [
                {
                  id: "D_test456",
                  number: 11058,
                  title: "Another Test Discussion",
                  url: "https://github.com/testowner/testrepo/discussions/11058",
                  body: "> AI generated by Test Workflow\n>\n> - [x] expires <!-- gh-aw-expires: 2020-01-20T09:20:00.000Z --> on Jan 20, 2020, 9:20 AM UTC",
                  createdAt: "2020-01-19T09:20:00.000Z",
                },
              ],
            },
          },
        })
        // Second call: hasExpirationComment - returns false (no comment exists)
        .mockResolvedValueOnce({
          node: {
            comments: {
              nodes: [{ body: "Some unrelated comment" }],
            },
          },
        })
        // Third call: addDiscussionComment
        .mockResolvedValueOnce({
          addDiscussionComment: {
            comment: {
              id: "C_comment123",
              url: "https://github.com/testowner/testrepo/discussions/11058#comment-123",
            },
          },
        })
        // Fourth call: closeDiscussionAsOutdated
        .mockResolvedValueOnce({
          closeDiscussion: {
            discussion: {
              id: "D_test456",
              url: "https://github.com/testowner/testrepo/discussions/11058",
            },
          },
        });

      await module.main();

      // Verify that we made 4 graphql calls (search, check comments, add comment, close)
      expect(mockGithub.graphql).toHaveBeenCalledTimes(4);

      // Verify that we added the comment
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("Adding closing comment"));

      // Verify that we closed the discussion
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("Discussion closed successfully"));
    });

    it("should handle empty comments gracefully", async () => {
      const module = await import("./close_expired_discussions.cjs");

      mockGithub.graphql
        // First call: searchDiscussionsWithExpiration
        .mockResolvedValueOnce({
          repository: {
            discussions: {
              pageInfo: {
                hasNextPage: false,
                endCursor: null,
              },
              nodes: [
                {
                  id: "D_test789",
                  number: 11059,
                  title: "Test Discussion with No Comments",
                  url: "https://github.com/testowner/testrepo/discussions/11059",
                  body: "> AI generated by Test Workflow\n>\n> - [x] expires <!-- gh-aw-expires: 2020-01-20T09:20:00.000Z --> on Jan 20, 2020, 9:20 AM UTC",
                  createdAt: "2020-01-19T09:20:00.000Z",
                },
              ],
            },
          },
        })
        // Second call: hasExpirationComment - empty comments
        .mockResolvedValueOnce({
          node: {
            comments: {
              nodes: [],
            },
          },
        })
        // Third call: addDiscussionComment
        .mockResolvedValueOnce({
          addDiscussionComment: {
            comment: {
              id: "C_comment456",
              url: "https://github.com/testowner/testrepo/discussions/11059#comment-456",
            },
          },
        })
        // Fourth call: closeDiscussionAsOutdated
        .mockResolvedValueOnce({
          closeDiscussion: {
            discussion: {
              id: "D_test789",
              url: "https://github.com/testowner/testrepo/discussions/11059",
            },
          },
        });

      await module.main();

      // Should add comment when no comments exist
      expect(mockGithub.graphql).toHaveBeenCalledTimes(4);
      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("Adding closing comment"));
    });
  });

  describe("main - no expired discussions", () => {
    it("should handle case with no discussions", async () => {
      const module = await import("./close_expired_discussions.cjs");

      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          discussions: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [],
          },
        },
      });

      await module.main();

      expect(mockCore.info).toHaveBeenCalledWith("No discussions with expiration markers found");
      expect(mockCore.summary.write).toHaveBeenCalled();
    });

    it("should handle non-expired discussions", async () => {
      const module = await import("./close_expired_discussions.cjs");

      // Mock a discussion that expires in the future
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 7); // 7 days from now

      mockGithub.graphql.mockResolvedValueOnce({
        repository: {
          discussions: {
            pageInfo: {
              hasNextPage: false,
              endCursor: null,
            },
            nodes: [
              {
                id: "D_future",
                number: 12000,
                title: "Future Discussion",
                url: "https://github.com/testowner/testrepo/discussions/12000",
                body: `> AI generated by Test Workflow\n>\n> - [x] expires <!-- gh-aw-expires: ${futureDate.toISOString()} --> on Future Date UTC`,
                createdAt: new Date().toISOString(),
              },
            ],
          },
        },
      });

      await module.main();

      expect(mockCore.info).toHaveBeenCalledWith(expect.stringContaining("is NOT expired"));
      expect(mockCore.info).toHaveBeenCalledWith("No expired discussions found");
    });
  });
});
