// @ts-check
// <reference types="@actions/github-script" />

const { getErrorMessage } = require("./error_helpers.cjs");

/**
 * Maximum number of issues to update per run
 */
const MAX_UPDATES_PER_RUN = 100;

/**
 * Delay between GraphQL API calls in milliseconds to avoid rate limiting
 */
const GRAPHQL_DELAY_MS = 500;

/**
 * Delay execution for a specified number of milliseconds
 * @param {number} ms - Milliseconds to delay
 * @returns {Promise<void>}
 */
function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Search for open issues with expiration markers
 * @param {any} github - GitHub GraphQL instance
 * @param {string} owner - Repository owner
 * @param {string} repo - Repository name
 * @returns {Promise<Array<{id: string, number: number, title: string, url: string, body: string, createdAt: string}>>} Matching issues
 */
async function searchIssuesWithExpiration(github, owner, repo) {
  const issues = [];
  let hasNextPage = true;
  let cursor = null;

  const { getErrorMessage } = require("./error_helpers.cjs");

  while (hasNextPage) {
    const query = `
      query($owner: String!, $repo: String!, $cursor: String) {
        repository(owner: $owner, name: $repo) {
          issues(first: 100, after: $cursor, states: [OPEN]) {
            pageInfo {
              hasNextPage
              endCursor
            }
            nodes {
              id
              number
              title
              url
              body
              createdAt
            }
          }
        }
      }
    `;

    const result = await github.graphql(query, {
      owner: owner,
      repo: repo,
      cursor: cursor,
    });

    if (!result || !result.repository || !result.repository.issues) {
      break;
    }

    const nodes = result.repository.issues.nodes || [];

    // Filter for issues with agentic workflow markers and expiration comments
    for (const issue of nodes) {
      // Check if created by an agentic workflow (body contains "> AI generated by" at start of line)
      const agenticPattern = /^> AI generated by/m;
      const isAgenticWorkflow = issue.body && agenticPattern.test(issue.body);

      if (!isAgenticWorkflow) {
        continue;
      }

      // Check if has expiration marker
      const expirationPattern = /<!-- gh-aw-expires: ([^>]+) -->/;
      const match = issue.body ? issue.body.match(expirationPattern) : null;

      if (match) {
        issues.push(issue);
      }
    }

    hasNextPage = result.repository.issues.pageInfo.hasNextPage;
    cursor = result.repository.issues.pageInfo.endCursor;
  }

  return issues;
}

/**
 * Extract expiration date from issue body
 * @param {string} body - Issue body
 * @returns {Date|null} Expiration date or null if not found/invalid
 */
function extractExpirationDate(body) {
  const expirationPattern = /<!-- gh-aw-expires: ([^>]+) -->/;
  const match = body.match(expirationPattern);

  if (!match) {
    return null;
  }

  const expirationISO = match[1].trim();
  const expirationDate = new Date(expirationISO);

  // Validate the date
  if (isNaN(expirationDate.getTime())) {
    return null;
  }

  return expirationDate;
}

/**
 * Validate issue creation date
 * @param {string} createdAt - ISO 8601 creation date
 * @returns {boolean} True if valid
 */
function validateCreationDate(createdAt) {
  const creationDate = new Date(createdAt);
  return !isNaN(creationDate.getTime());
}

/**
 * Add comment to a GitHub Issue using REST API
 * @param {any} github - GitHub REST instance
 * @param {string} owner - Repository owner
 * @param {string} repo - Repository name
 * @param {number} issueNumber - Issue number
 * @param {string} message - Comment body
 * @returns {Promise<any>} Comment details
 */
async function addIssueComment(github, owner, repo, issueNumber, message) {
  const result = await github.rest.issues.createComment({
    owner: owner,
    repo: repo,
    issue_number: issueNumber,
    body: message,
  });

  return result.data;
}

/**
 * Close a GitHub Issue using REST API
 * @param {any} github - GitHub REST instance
 * @param {string} owner - Repository owner
 * @param {string} repo - Repository name
 * @param {number} issueNumber - Issue number
 * @returns {Promise<any>} Issue details
 */
async function closeIssue(github, owner, repo, issueNumber) {
  const result = await github.rest.issues.update({
    owner: owner,
    repo: repo,
    issue_number: issueNumber,
    state: "closed",
    state_reason: "not_planned",
  });

  return result.data;
}

async function main() {
  const owner = context.repo.owner;
  const repo = context.repo.repo;

  core.info(`Searching for expired issues in ${owner}/${repo}`);

  // Search for issues with expiration markers
  const issuesWithExpiration = await searchIssuesWithExpiration(github, owner, repo);

  if (issuesWithExpiration.length === 0) {
    core.info("No issues with expiration markers found");
    return;
  }

  core.info(`Found ${issuesWithExpiration.length} issue(s) with expiration markers`);

  // Check which issues are expired
  const now = new Date();
  const expiredIssues = [];

  for (const issue of issuesWithExpiration) {
    // Validate creation date
    if (!validateCreationDate(issue.createdAt)) {
      core.warning(`Issue #${issue.number} has invalid creation date, skipping`);
      continue;
    }

    // Extract and validate expiration date
    const expirationDate = extractExpirationDate(issue.body);
    if (!expirationDate) {
      core.warning(`Issue #${issue.number} has invalid expiration date, skipping`);
      continue;
    }

    // Check if expired
    if (now >= expirationDate) {
      expiredIssues.push({
        ...issue,
        expirationDate: expirationDate,
      });
    }
  }

  if (expiredIssues.length === 0) {
    core.info("No expired issues found");
    return;
  }

  core.info(`Found ${expiredIssues.length} expired issue(s)`);

  // Limit to MAX_UPDATES_PER_RUN
  const issuesToClose = expiredIssues.slice(0, MAX_UPDATES_PER_RUN);

  if (expiredIssues.length > MAX_UPDATES_PER_RUN) {
    core.warning(`Found ${expiredIssues.length} expired issues, but only closing the first ${MAX_UPDATES_PER_RUN}`);
  }

  let closedCount = 0;
  const closedIssues = [];

  for (let i = 0; i < issuesToClose.length; i++) {
    const issue = issuesToClose[i];

    try {
      const closingMessage = `This issue was automatically closed because it expired on ${issue.expirationDate.toISOString()}.`;

      // Add comment first
      core.info(`Adding closing comment to issue #${issue.number}`);
      await addIssueComment(github, owner, repo, issue.number, closingMessage);

      // Then close the issue as not planned
      core.info(`Closing issue #${issue.number} as not planned`);
      await closeIssue(github, owner, repo, issue.number);

      closedIssues.push({
        number: issue.number,
        url: issue.url,
        title: issue.title,
      });

      closedCount++;
      core.info(`✓ Closed issue #${issue.number}: ${issue.url}`);
    } catch (error) {
      core.error(`✗ Failed to close issue #${issue.number}: ${getErrorMessage(error)}`);
      // Continue with other issues even if one fails
    }

    // Add delay between GraphQL operations to avoid rate limiting (except for the last item)
    if (i < issuesToClose.length - 1) {
      await delay(GRAPHQL_DELAY_MS);
    }
  }

  // Write summary
  if (closedCount > 0) {
    let summaryContent = `## Closed Expired Issues\n\n`;
    summaryContent += `Closed **${closedCount}** expired issue(s):\n\n`;
    for (const closed of closedIssues) {
      summaryContent += `- Issue #${closed.number}: [${closed.title}](${closed.url})\n`;
    }
    await core.summary.addRaw(summaryContent).write();
  }

  core.info(`Successfully closed ${closedCount} expired issue(s)`);
}

module.exports = { main };
