// @ts-check

/**
 * Copilot SDK Driver
 *
 * Uses @github/copilot-sdk to drive a Copilot session against a running headless
 * Copilot CLI server (started by copilot_sdk_sidecar.cjs).  Serializes all SDK
 * session events to a JSONL file so that unified_timeline.cjs can render them.
 *
 * Event mapping:
 *   SDK "user.message"          → JSONL "user.message"
 *   SDK "tool.execution_start"  → JSONL "tool.execution_start"  (toolName, mcpServerName)
 *   SDK "tool.execution_complete" → JSONL "tool.execution_complete" (toolName, mcpServerName, success)
 *   SDK "assistant.message"     → JSONL "assistant.message"     (content)
 *
 * The JSONL file is written to:
 *   /tmp/gh-aw/sandbox/agent/logs/copilot-session-state/{sessionId}/events.jsonl
 * which mirrors the path that copy_copilot_session_state.sh produces and that
 * unified_timeline.cjs reads.
 *
 * When run as a standalone program (require.main === module), the driver reads
 * configuration from environment variables and connects to the sidecar server
 * that has already been started by copilot_harness.cjs:
 *
 *   GH_AW_PROMPT              — path to the prompt file
 *   COPILOT_SDK_URI            — SDK server URI (set by the harness)
 *   COPILOT_CONNECTION_TOKEN   — shared secret for the SDK session (set by the harness)
 *   COPILOT_MODEL              — model override (optional)
 *
 * The sidecar is started and stopped by the harness; the driver only opens a
 * client connection, runs the session, and exits.  This makes the driver a
 * simple client extension that can be started by the harness like any other
 * command, while serving as a sample showing how to create a Copilot SDK driver
 * extension in agentic-workflows.
 */

"use strict";

const fs = require("fs");
const { runWithCopilotSDK } = require("./copilot_sdk_runner.cjs");

/**
 * Extract the prompt text from a resolved args array.
 * Looks for the first occurrence of "-p <value>" or "--prompt <value>".
 *
 * @param {string[]} args - Resolved args (after resolvePromptFileArgs has run).
 * @returns {string | null} The prompt text, or null if not found.
 */
function extractPromptFromArgs(args) {
  for (let i = 0; i < args.length - 1; i++) {
    if (args[i] === "-p" || args[i] === "--prompt") {
      return args[i + 1];
    }
  }
  return null;
}

module.exports = { extractPromptFromArgs, runWithCopilotSDK };

// ---------------------------------------------------------------------------
// Standalone entry point
// ---------------------------------------------------------------------------

/**
 * Log a message prefixed with [copilot-sdk-driver] to stderr.
 * @param {string} msg
 */
function log(msg) {
  process.stderr.write(`[copilot-sdk-driver] ${msg}\n`);
}

/**
 * Entry point when the driver is run directly with Node:
 *   node copilot_sdk_driver.cjs
 *
 * Reads configuration from environment variables and connects to the headless
 * Copilot CLI sidecar that has already been started by copilot_harness.cjs.
 * Runs a single SDK session and exits with the session's exit code.
 * Any unhandled error causes a non-zero exit.
 */
async function main() {
  // --- Read configuration from environment ---------------------

  const promptFile = process.env.GH_AW_PROMPT;
  if (!promptFile) {
    process.stderr.write("[copilot-sdk-driver] error: GH_AW_PROMPT is not set\n");
    process.exit(1);
  }

  const sdkUri = process.env.COPILOT_SDK_URI;
  if (!sdkUri) {
    process.stderr.write("[copilot-sdk-driver] error: COPILOT_SDK_URI is not set\n");
    process.exit(1);
  }

  const model = process.env.COPILOT_MODEL || undefined;
  const connectionToken = process.env.COPILOT_CONNECTION_TOKEN;
  if (!connectionToken) {
    process.stderr.write("[copilot-sdk-driver] error: COPILOT_CONNECTION_TOKEN is required. This token is generated by copilot_harness.cjs and must be passed to the driver environment\n");
    process.exit(1);
  }

  // --- Read the prompt -------------------------------------------------

  let prompt;
  try {
    prompt = fs.readFileSync(promptFile, "utf8");
  } catch (err) {
    process.stderr.write(`[copilot-sdk-driver] error: failed to read prompt file ${promptFile}: ${err}\n`);
    process.exit(1);
  }

  log(`connecting to sidecar at ${sdkUri}`);

  // --- Resolve BYOK custom provider from environment ------------------
  // The harness resolves the BYOK provider from live AWF reflect data before launching
  // this driver and injects the result as GH_AW_COPILOT_SDK_PROVIDER_BASE_URL.
  // BYOK is the only supported mode — fail immediately if the env var is missing.
  const providerBaseUrl = process.env.GH_AW_COPILOT_SDK_PROVIDER_BASE_URL;
  if (!providerBaseUrl) {
    process.stderr.write("[copilot-sdk-driver] error: GH_AW_COPILOT_SDK_PROVIDER_BASE_URL is not set — " + "BYOK provider is required; ensure the harness resolved a custom provider from awf-reflect data\n");
    process.exit(1);
  }
  /** @type {import("@github/copilot-sdk").ProviderConfig} */
  const provider = { type: "openai", baseUrl: providerBaseUrl };

  // --- Run SDK session -------------------------------------------------

  const result = await runWithCopilotSDK({
    sdkUri,
    prompt,
    logger: log,
    model,
    connectionToken,
    provider,
  });

  process.exit(result.exitCode);
}

if (require.main === module) {
  main().catch(err => {
    process.stderr.write(`[copilot-sdk-driver] unhandled error: ${err instanceof Error ? err.stack : String(err)}\n`);
    process.exit(1);
  });
}
