// @ts-check
/// <reference types="@actions/github-script" />

/**
 * Body Header Message Module
 *
 * This module provides the body-header and disclosure-header generation for safe-output workflows.
 * The body header is prepended to every message body generated by safe outputs
 * (issues, comments, pull requests, discussions).
 */

const { getMessages, renderTemplate, toSnakeCase } = require("./messages_core.cjs");

/**
 * @typedef {Object} BodyHeaderContext
 * @property {string} workflowName - Name of the workflow
 * @property {string} runUrl - URL of the workflow run
 */

/**
 * Default AI authorship disclosure text used when disclosure-header is set to true.
 * Rendered with the same template placeholders as other message templates.
 */
const DEFAULT_DISCLOSURE_HEADER = "> 🤖 **Automated content** — generated by the [{workflow_name}]({run_url}) workflow. The account owner did **not** write or review this content personally.";

/**
 * Get the body header text, using the custom template if configured.
 * Returns an empty string when no body-header is configured.
 * @param {BodyHeaderContext} ctx - Context for header generation
 * @returns {string} The rendered header text, or empty string if not configured
 */
function getBodyHeader(ctx) {
  const messages = getMessages();
  if (!messages?.bodyHeader) {
    return "";
  }

  const templateContext = toSnakeCase(ctx);
  return renderTemplate(messages.bodyHeader, templateContext);
}

/**
 * Get the AI authorship disclosure header text.
 * When disclosure-header is "true", returns the built-in default AI disclosure text.
 * When disclosure-header is a custom string, renders it as a template.
 * Returns an empty string when disclosure-header is not configured.
 * @param {BodyHeaderContext} ctx - Context for header generation
 * @returns {string} The rendered disclosure header text, or empty string if not configured
 */
function getDisclosureHeader(ctx) {
  const messages = getMessages();
  if (!messages?.disclosureHeader) {
    return "";
  }

  const templateContext = toSnakeCase(ctx);
  const template = messages.disclosureHeader === "true" ? DEFAULT_DISCLOSURE_HEADER : messages.disclosureHeader;
  return renderTemplate(template, templateContext);
}

module.exports = {
  getBodyHeader,
  getDisclosureHeader,
  DEFAULT_DISCLOSURE_HEADER,
};
