// @ts-check
/// <reference types="@actions/github-script" />

/**
 * Body Header Message Module
 *
 * This module provides the body-header and disclosure-header generation for safe-output workflows.
 * The body header is prepended to every message body generated by safe outputs
 * (issues, comments, pull requests, discussions).
 */

const fs = require("fs");
const path = require("path");
const { getMessages, getPromptPath, renderTemplate, toSnakeCase } = require("./messages_core.cjs");

/**
 * @typedef {Object} BodyHeaderContext
 * @property {string} workflowName - Name of the workflow
 * @property {string} runUrl - URL of the workflow run
 */

const DEFAULT_DISCLOSURE_HEADER_TEMPLATE = "safe_outputs_disclosure_header.md";
const DEFAULT_DISCLOSURE_HEADER_FALLBACK = "> 🤖 **Automated content** — generated by the [{workflow_name}]({run_url}) workflow. The account owner did **not** write or review this content personally.";
const DISCLOSURE_HEADER_DEFAULT_SENTINEL = "true";

/**
 * Load the default disclosure-header template from prompt markdown.
 * Falls back to an inline template if the file is unavailable.
 * @returns {string}
 */
function getDefaultDisclosureHeaderTemplate() {
  try {
    const shouldUseRuntimePrompts = !!(process.env.RUNNER_TEMP || process.env.GH_AW_PROMPTS_DIR);
    const templatePath = shouldUseRuntimePrompts ? getPromptPath(DEFAULT_DISCLOSURE_HEADER_TEMPLATE) : path.join(__dirname, "../md", DEFAULT_DISCLOSURE_HEADER_TEMPLATE);
    return fs.readFileSync(templatePath, "utf8").trimEnd();
  } catch {
    return DEFAULT_DISCLOSURE_HEADER_FALLBACK;
  }
}

const DEFAULT_DISCLOSURE_HEADER = getDefaultDisclosureHeaderTemplate();

/**
 * Get the body header text, using the custom template if configured.
 * Returns an empty string when no body-header is configured.
 * @param {BodyHeaderContext} ctx - Context for header generation
 * @returns {string} The rendered header text, or empty string if not configured
 */
function getBodyHeader(ctx) {
  const messages = getMessages();
  if (!messages?.bodyHeader) {
    return "";
  }

  const templateContext = toSnakeCase(ctx);
  return renderTemplate(messages.bodyHeader, templateContext);
}

/**
 * Get the AI authorship disclosure header text.
 * When disclosure-header is "true", returns the built-in default AI disclosure text.
 * When disclosure-header is a custom string, renders it as a template.
 * Returns an empty string when disclosure-header is not configured.
 * @param {BodyHeaderContext} ctx - Context for header generation
 * @returns {string} The rendered disclosure header text, or empty string if not configured
 */
function getDisclosureHeader(ctx) {
  const messages = getMessages();
  const disclosureHeader = messages?.disclosureHeader;
  if (!disclosureHeader) {
    return "";
  }

  let template = "";
  if (disclosureHeader === true || disclosureHeader === DISCLOSURE_HEADER_DEFAULT_SENTINEL) {
    template = DEFAULT_DISCLOSURE_HEADER;
  } else if (typeof disclosureHeader === "string") {
    template = disclosureHeader;
  } else {
    return "";
  }

  const templateContext = toSnakeCase(ctx);
  return renderTemplate(template, templateContext);
}

module.exports = {
  getBodyHeader,
  getDisclosureHeader,
  DEFAULT_DISCLOSURE_HEADER,
  DISCLOSURE_HEADER_DEFAULT_SENTINEL,
};
