import { describe, it, expect, beforeEach, vi } from "vitest";

// Mock the global objects that GitHub Actions provides
const mockCore = {
  debug: vi.fn(),
  info: vi.fn(),
  notice: vi.fn(),
  warning: vi.fn(),
  error: vi.fn(),
  setFailed: vi.fn(),
  setOutput: vi.fn(),
  summary: {
    addRaw: vi.fn().mockReturnThis(),
    write: vi.fn().mockResolvedValue(),
  },
};

const mockGithub = {
  rest: {
    issues: {
      get: vi.fn(),
      update: vi.fn(),
    },
  },
};

const mockContext = {
  eventName: "issues",
  repo: {
    owner: "testowner",
    repo: "testrepo",
  },
  serverUrl: "https://github.com",
  runId: 12345,
  payload: {
    issue: {
      number: 100,
    },
  },
};

// Set up global mocks
global.core = mockCore;
global.github = mockGithub;
global.context = mockContext;

describe("update_issue.cjs - footer support", () => {
  beforeEach(async () => {
    // Reset all mocks before each test
    vi.clearAllMocks();
    vi.resetModules();

    // Reset environment variables
    process.env.GH_AW_WORKFLOW_NAME = "Test Workflow";

    // Reset mock implementations
    mockGithub.rest.issues.get.mockResolvedValue({
      data: {
        number: 100,
        title: "Test Issue",
        body: "Original body content",
        html_url: "https://github.com/testowner/testrepo/issues/100",
      },
    });

    mockGithub.rest.issues.update.mockResolvedValue({
      data: {
        number: 100,
        title: "Test Issue",
        body: "Updated body",
        html_url: "https://github.com/testowner/testrepo/issues/100",
      },
    });
  });

  describe("Footer addition", () => {
    it("should add footer when using append operation", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original content",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content to append";
      const expectedBody = `Original content\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Verify expected body contains all required parts
      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain("---");
      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("> AI generated by");
      expect(expectedBody).toContain("[Test Workflow]");
      // Original content should come first
      expect(expectedBody.indexOf("Original content")).toBeLessThan(expectedBody.indexOf(newContent));
    });

    it("should add footer when using prepend operation", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original content",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content to prepend";
      const expectedBody = `${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n\n---\n\nOriginal content`;

      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("> AI generated by");
      expect(expectedBody).toContain("[Test Workflow]");
      // New content should come first
      expect(expectedBody.indexOf(newContent)).toBeLessThan(expectedBody.indexOf("Original content"));
    });

    it("should use custom workflow name from environment", async () => {
      process.env.GH_AW_WORKFLOW_NAME = "Custom Issue Workflow";

      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `Original\n\n---\n\n${newContent}\n\n> AI generated by [Custom Issue Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("Custom Issue Workflow");
      expect(expectedBody).not.toContain("Test Workflow");
    });

    it("should use default workflow name when not set", async () => {
      delete process.env.GH_AW_WORKFLOW_NAME;

      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `Original\n\n---\n\n${newContent}\n\n> AI generated by [GitHub Agentic Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      expect(expectedBody).toContain("GitHub Agentic Workflow");
    });

    it("should handle null body as empty string", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: null,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New content";
      const expectedBody = `\n\n---\n\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)`;

      // Should work same as empty string
      expect(expectedBody).toContain(newContent);
      expect(expectedBody).toContain("> AI generated by");
    });
  });

  describe("Replace-island operation", () => {
    it("should create new island when not found", async () => {
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: "Original content",
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "Island content";
      const expectedBody = `Original content\n\n---\n\n<!-- gh-aw-island-start:12345 -->\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:12345 -->`;

      expect(expectedBody).toContain("Original content");
      expect(expectedBody).toContain("Island content");
      expect(expectedBody).toContain("<!-- gh-aw-island-start:12345 -->");
      expect(expectedBody).toContain("<!-- gh-aw-island-end:12345 -->");
      expect(expectedBody).toContain("> AI generated by");
    });

    it("should replace existing island content", async () => {
      const existingBody = "Before\n<!-- gh-aw-island-start:12345 -->\nOld island\n<!-- gh-aw-island-end:12345 -->\nAfter";
      mockGithub.rest.issues.get.mockResolvedValueOnce({
        data: {
          number: 100,
          title: "Test Issue",
          body: existingBody,
          html_url: "https://github.com/testowner/testrepo/issues/100",
        },
      });

      const newContent = "New island";
      const expectedBody = `Before\n<!-- gh-aw-island-start:12345 -->\n${newContent}\n\n> AI generated by [Test Workflow](https://github.com/testowner/testrepo/actions/runs/12345)\n<!-- gh-aw-island-end:12345 -->\nAfter`;

      expect(expectedBody).toContain("Before");
      expect(expectedBody).toContain("After");
      expect(expectedBody).toContain("New island");
      expect(expectedBody).not.toContain("Old island");
      expect(expectedBody).toContain("> AI generated by");
    });
  });

  describe("Replace operation", () => {
    it("should replace entire body without fetching current content", () => {
      // The replace operation should NOT fetch the current issue
      // It just replaces the entire body
      const newContent = "New body content";

      // With replace operation, the body is used directly without fetching current content
      // This test verifies that replace doesn't call get
      expect(mockGithub.rest.issues.get).not.toHaveBeenCalled();
    });
  });
});
