version: "2"

run:
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    errcheck:
      # Disable errcheck for test files - system calls in tests don't need error handling
      exclude-functions:
        - (*os.File).Close
        - (*os.File).Sync
        - os.Chdir
        - os.Chmod
        - os.Chtimes
        - os.MkdirAll
        - os.Remove
        - os.RemoveAll
        - os.WriteFile
  exclusions:
    rules:
      # Disable errcheck for all test files
      - linters:
          - errcheck
        path: _test\.go

      # Disable noisy revive rules repository-wide
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: var-naming
      - linters:
          - revive
        text: redefines-builtin-id
      - linters:
          - revive
        text: indent-error-flow
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: exported

formatters:
  enable:
    - gofmt
    - goimports
