version: "2"
run:
  tests: true
linters:
  enable:
    - misspell
    - revive
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*os.File).Sync
        - os.Chdir
        - os.Chmod
        - os.Chtimes
        - os.MkdirAll
        - os.Remove
        - os.RemoveAll
        - os.WriteFile
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: var-naming
      - linters:
          - revive
        text: redefines-builtin-id
      - linters:
          - revive
        text: indent-error-flow
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: exported
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
