version: "2"
run:
  tests: true
linters:
  enable:
    - misspell
    - revive
    - modernize      # Modern Go patterns (NEW in v2.6.0)
    - gocritic       # Comprehensive opinionated linter
    - gosec          # Security-focused
    # godot linter disabled - too pedantic about comment punctuation
    - unconvert      # Remove unnecessary conversions
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*os.File).Sync
        - os.Chdir
        - os.Chmod
        - os.Chtimes
        - os.MkdirAll
        - os.Remove
        - os.RemoveAll
        - os.WriteFile
    gocritic:
      disabled-checks:
        - ifElseChain      # else-if chains are often clearer than switches
        - singleCaseSwitch # Single case switches can be intentional for consistency
        - appendAssign     # Appending to different variable is often intentional
        - unlambda         # Explicit lambdas can be clearer than direct function refs
        - elseif           # else-if pattern is acceptable
        - assignOp         # Long form assignment can be clearer
        - argOrder         # False positives on string contains
        - dupBranchBody    # Duplicate branches can be intentional for clarity
    gosec:
      excludes:
        - G101 # Ignore "Potential hardcoded credentials" - often false positives
        - G602 # Ignore "slice bounds check" - handled by runtime
        - G115 # Ignore "integer overflow conversion" - acceptable in most cases
        - G301 # Ignore "file permissions" - 0644 is acceptable for non-sensitive files
      config:
        G204: "0644" # Allow common file permissions in tests
        G306: "0644" # Allow common file permissions
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: var-naming
      - linters:
          - revive
        text: redefines-builtin-id
      - linters:
          - revive
        text: indent-error-flow
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: exported
      - linters:
          - gosec
        text: "G204" # Allow exec.Command in controlled contexts
        path: pkg/awmg/gateway\.go
      - linters:
          - gosec
        text: "G204" # Allow docker commands in actionlint
        path: pkg/cli/actionlint\.go
      - linters:
          - gosec
        text: "G204" # Allow git commands in remote_fetch
        path: pkg/parser/remote_fetch\.go
      - linters:
          - gosec
        text: "G404" # Allow math/rand for non-crypto purposes
        path: pkg/cli/(add_command|update_git)\.go
      - linters:
          - gosec
        text: "G306" # Allow 0644 permissions in test files
        path: _test\.go
      - linters:
          - gosec
        text: "G305" # Allow file path operations in logs_download
        path: pkg/cli/logs_download\.go
      - linters:
          - gosec
        text: "G110" # Allow decompression in logs_download
        path: pkg/cli/logs_download\.go
      - linters:
          - gocritic
        text: "deprecatedComment" # Allow existing deprecated comment format
      - linters:
          - gocritic
        text: "commentFormatting" # Allow commented out code
      - linters:
          - gocritic
        text: "badCall" # filepath.Join with 1 arg is acceptable
      - linters:
          - godot
        path: _test\.go # Don't require periods in test comments
      - linters:
          - modernize
        text: "omitzero" # omitzero is acceptable for struct tags
      - linters:
          - modernize
        text: "mapsloop" # maps.Copy requires Go 1.21+, keep compatible
      - linters:
          - modernize
        text: "bloop" # b.Loop() is new, keep compatible with older Go
      - linters:
          - modernize
        text: "minmax" # min/max builtins are Go 1.21+, keep compatible
      - linters:
          - modernize
        text: "forvar" # Copying loop variable is sometimes clearer
      - linters:
          - modernize
        text: "plusbuild" # Keep build constraint for compatibility
        path: shell_backslash_integration_test\.go
      - linters:
          - modernize
        text: "any" # Keep interface{} for clarity in schema tests
        path: schema_strict_documentation_test\.go
      - linters:
          - modernize
        text: "any" # Keep interface{} for clarity in tests
        path: logs_awinfo_backward_compat_test\.go
      - linters:
          - modernize
        text: "rangeint" # Keep traditional loops for compatibility
      - linters:
          - modernize
        text: "stringsseq" # SplitSeq requires Go 1.23+, keep compatible
      - linters:
          - modernize
        text: "slicescontains" # slices.Contains requires Go 1.21+
      - linters:
          - modernize
        text: "stringscutprefix" # strings.Cut* requires Go 1.20+
      - linters:
          - modernize
        text: "stringsbuilder" # Minor optimization, acceptable pattern
      - linters:
          - modernize
        text: "reflecttypefor" # TypeFor requires Go 1.22+
      - linters:
          - unconvert
        path: _test\.go # Allow explicit conversions in tests for clarity
      - linters:
          - gosec
        text: "G204" # Allow git commands in download_workflow
        path: pkg/cli/download_workflow\.go
      - linters:
          - gosec
        text: "G204" # Allow exec.Command with config in mcp_inspect
        path: pkg/cli/mcp_inspect\.go
      - linters:
          - gosec
        text: "G204" # Allow exec.Command with config in mcp_inspect_mcp
        path: pkg/cli/mcp_inspect_mcp\.go
      - linters:
          - gosec
        text: "G306" # 0755 is correct permission for executable script
        path: pkg/cli/mcp_inspect\.go
      - linters:
          - gosec
        text: "G306" # 0755 is correct permission for shell scripts
        path: pkg/cli/actions_build_command\.go
      - linters:
          - gosec
        text: "G204" # Allow docker commands in poutine
        path: pkg/cli/poutine\.go
      - linters:
          - gosec
        text: "G204" # Allow node command in tests
        path: pkg/workflow/js_comments_test\.go
      - linters:
          - gosec
        text: "G204" # Allow npx command in integration tests
        path: pkg/workflow/playwright_mcp_integration_test\.go
      - linters:
          - gosec
        text: "G204" # Allow exec of binary in status tests
        path: pkg/cli/status_command_test\.go
      - linters:
          - gosec
        text: "G204" # Allow docker commands in zizmor
        path: pkg/cli/zizmor\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
