version: '2'

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - revive
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
