package workflow

import (
	"strings"

	"github.com/githubnext/gh-aw/pkg/logger"
)

var checkpointPromptLog = logger.New("workflow:checkpoint_prompt")

// GenerateCheckpointRecordingPromptStep generates instructions for the agent to record checkpoints
func (c *Compiler) generateCheckpointRecordingPromptStep(yaml *strings.Builder, data *WorkflowData) {
	if !ShouldEnableTraceCapture(data) {
		return
	}

	checkpointPromptLog.Print("Adding checkpoint recording instructions to prompt")

	yaml.WriteString("      - name: Append checkpoint recording instructions to prompt\n")
	yaml.WriteString("        env:\n")
	yaml.WriteString("          GH_AW_PROMPT: /tmp/gh-aw/aw-prompts/prompt.txt\n")
	yaml.WriteString("        run: |\n")
	yaml.WriteString("          cat >> \"$GH_AW_PROMPT\" << 'CHECKPOINT_EOF'\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          ## Checkpoint Recording Instructions\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          **IMPORTANT**: As you work, record checkpoints to create a replayable execution trace.\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          ### When to Record Checkpoints\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          Record a checkpoint after each significant step:\n")
	yaml.WriteString("          - After gathering information (tool calls, searches, file reads)\n")
	yaml.WriteString("          - After making code changes (edits, patches, refactors)\n")
	yaml.WriteString("          - After running validations (tests, lints, builds, checks)\n")
	yaml.WriteString("          - Before safe-output operations (creating PRs, issues, comments)\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          ### How to Record a Checkpoint\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          Use this bash command:\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          ```bash\n")
	yaml.WriteString("          bash /tmp/gh-aw/record_checkpoint.sh <type> <description>\n")
	yaml.WriteString("          ```\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          **Checkpoint Types:**\n")
	yaml.WriteString("          - `tool_call` - Gathered information via tool/search/read\n")
	yaml.WriteString("          - `patch` - Modified files\n")
	yaml.WriteString("          - `eval` - Ran validation/tests\n")
	yaml.WriteString("          - `safe_output` - Creating PR/issue/comment\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          **Examples:**\n")
	yaml.WriteString("          ```bash\n")
	yaml.WriteString("          # After searching/reading\n")
	yaml.WriteString("          bash /tmp/gh-aw/record_checkpoint.sh tool_call \"Found 12 test files in pkg/\"\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          # After editing files\n")
	yaml.WriteString("          bash /tmp/gh-aw/record_checkpoint.sh patch \"Fixed error handling in 3 files\"\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          # After running validation\n")
	yaml.WriteString("          bash /tmp/gh-aw/record_checkpoint.sh eval \"Tests passed: 45/45\"\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          # Before creating output\n")
	yaml.WriteString("          bash /tmp/gh-aw/record_checkpoint.sh safe_output \"Creating PR with bug fixes\"\n")
	yaml.WriteString("          ```\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          ### Good Descriptions\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          Include concrete details:\n")
	yaml.WriteString("          - What was done (action verb + object)\n")
	yaml.WriteString("          - Counts/numbers when relevant\n")
	yaml.WriteString("          - Key files/paths when relevant\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          **Good:** \"Analyzed 5 test files, found 2 failures\"\n")
	yaml.WriteString("          **Bad:** \"Did some analysis\"\n")
	yaml.WriteString("          - Important context (counts, file names, etc.)\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          **Good:** \"Analyzed 5 test files, found 2 failures\"\n")
	yaml.WriteString("          **Bad:** \"Did some analysis\"\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          These checkpoints enable:\n")
	yaml.WriteString("          - Debugging failed runs (see exactly where things went wrong)\n")
	yaml.WriteString("          - Replay from any checkpoint (restart with cached responses)\n")
	yaml.WriteString("          - Timeline view (Job Summary shows clickable checkpoint table)\n")
	yaml.WriteString("          \n")
	yaml.WriteString("          CHECKPOINT_EOF\n")
}
