//go:build !integration

package workflow

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCommentMemorySupportWorkflowDocumentsSpecRequirements(t *testing.T) {
	workflowPath := findRepoFile(t, filepath.Join(".github", "workflows", "comment-memory-support.md"))
	workflowBytes, err := os.ReadFile(workflowPath)
	require.NoError(t, err, "should read comment-memory support workflow")

	spec := string(workflowBytes)
	expectedRequirements := []string{
		"`comment-memory`",
		"one or more memories",
		"issue or pull request",
		"Create memory comment",
		"Update existing memory comment",
		"XML markers",
		"PR-review style workflows",
		"text and test detection gates",
		"ADR gates",
		"Codex smoke checks",
		"Safe Output MCP flows",
		"main safe-output handler job behavior",
		"default GitHub token",
		"custom GitHub token",
		"GitHub App authentication",
		"external repositories",
		"sanitization",
		"size limits",
		"`Generated by AI` footer",
	}

	for _, expected := range expectedRequirements {
		assert.Contains(t, spec, expected, "workflow spec should include requirement: %s", expected)
	}
}
