package workflow

import (
	"fmt"
	"strings"

	"github.com/github/gh-aw/pkg/logger"
)

var consolidatedSafeOutputsStepsLog = logger.New("workflow:compiler_safe_outputs_steps")

// buildSharedPRCheckoutSteps builds checkout and git-configuration steps for the
// safe_outputs job's create-pull-request / push-to-pull-request-branch operations.
//
// The checkout steps are generated by the SAME CheckoutManager generators the agent job
// uses (GenerateCheckoutAppTokenSteps, GenerateDefaultCheckoutStep,
// GenerateAdditionalCheckoutSteps), so the safe_outputs job lays out every repository on
// disk identically to the agent job. The only safe_outputs-specific differences are:
//   - a per-step `if:` condition gating the steps on whether a create_pull_request /
//     push_to_pull_request_branch output will actually be processed, and
//   - a trailing "Configure Git credentials" step that installs a push-capable token
//     (the agent job never pushes, so it omits this).
//
// Base-branch selection is intentionally NOT done here. The JS handler resolves the base
// branch per target repository at apply time (it runs `git fetch origin <base>` and
// branches from `origin/<base>` in the target repo's directory), so a checkout-time base
// ref is unnecessary. This is the same mechanism the multi-repo path already relied on.
func (c *Compiler) buildSharedPRCheckoutSteps(data *WorkflowData) []string {
	consolidatedSafeOutputsStepsLog.Print("Building shared PR checkout steps (mirroring agent job layout)")

	// Build the same CheckoutManager the agent job builds from the workflow's checkout: config.
	checkoutMgr := NewCheckoutManager(data.CheckoutConfigs)

	// Unlike the agent job, the safe_outputs job performs git fetch/push against the
	// checked-out repositories (create_pull_request, push_to_pull_request_branch), so its
	// checkouts must retain credentials (persist-credentials: true) instead of stripping
	// them. This keeps the push-capable token on disk for the handlers; the trusted
	// safe_outputs handler code (not the untrusted agent) is the only consumer.
	checkoutMgr.SetKeepCredentialsForPush(true)

	// Persist the resolved PR push token (not just the default GITHUB_TOKEN) into
	// .git/config so the retained credential matches the token the handlers use to
	// fetch/push. This keeps a single, correct Authorization header on the wire and
	// removes the need for the handlers to inject a separate http.extraheader. The
	// same token is reused below for the "Configure Git credentials" step so both the
	// persisted checkout credential and the push remote agree on a single token.
	prCheckoutToken, _ := resolvePRCheckoutToken(data.SafeOutputs, checkoutMgr)
	checkoutMgr.SetPushToken(resolveStaticCheckoutToken(data.SafeOutputs, checkoutMgr))

	// Combined condition: run the checkout/git-config steps only when a create_pull_request
	// or push_to_pull_request_branch output will be processed.
	condition := buildPRCheckoutCondition(data.SafeOutputs)

	var steps []string

	// Mint checkout app tokens (identical to the agent job) when any checkout uses app auth.
	// These must live in the safe_outputs job because the minted token is referenced by the
	// checkout steps via ${{ steps.checkout-app-token-N.outputs.token }} within the same job.
	if checkoutMgr.HasAppAuth() {
		steps = append(steps, injectStepCondition(checkoutMgr.GenerateCheckoutAppTokenSteps(c, resolveCheckoutPermissions(data)), condition)...)
	}
	if checkoutMgr.HasSafeOutputAppAuth() {
		steps = append(steps, checkoutMgr.GenerateSafeOutputCheckoutAppTokenSteps(c, resolveCheckoutPermissions(data))...)
	}

	// Default workspace checkout (identical to the agent job).
	steps = append(steps, injectStepCondition(
		checkoutMgr.GenerateDefaultCheckoutStep(c.trialMode, c.trialLogicalRepoSlug, c.getActionPin),
		condition,
	)...)

	// Additional (cross-repo / subdirectory) checkouts (identical to the agent job).
	steps = append(steps, injectStepCondition(
		checkoutMgr.GenerateAdditionalCheckoutSteps(c.getActionPin),
		condition,
	)...)

	// Configure Git credentials so the safe_outputs job can push. The agent job never
	// pushes, so this step has no agent-job equivalent. Reuse the token resolved above so
	// the push remote and the persisted checkout credential use the same token.
	steps = append(steps, checkoutMgr.GenerateConfigureGitCredentialsSteps(prCheckoutToken, condition)...)

	consolidatedSafeOutputsStepsLog.Printf("Built shared PR checkout steps with condition: %s", condition.Render())
	return steps
}

// buildHandlerManagerStep builds a single step that uses the safe output handler manager
// to dispatch messages to appropriate handlers. This replaces multiple individual steps
// with a single dispatcher step that processes all safe output types.
func (c *Compiler) buildHandlerManagerStep(data *WorkflowData) ([]string, error) {
	consolidatedSafeOutputsStepsLog.Print("Building handler manager step")

	var steps []string
	steps = append(steps, c.buildCreateCheckRunAppTokenSteps(data)...)
	steps = append(steps, buildHandlerManagerStepHeader(data)...)
	if err := c.addHandlerManagerEnv(&steps, data); err != nil {
		return nil, err
	}
	steps = append(steps, "        with:\n")
	configToken := ""
	if data.SafeOutputs != nil && data.SafeOutputs.GitHubToken != "" {
		configToken = data.SafeOutputs.GitHubToken
	}
	c.addSafeOutputGitHubTokenForConfig(&steps, data, configToken)
	steps = append(steps, buildHandlerManagerScriptLines()...)
	return steps, nil
}

func (c *Compiler) buildCreateCheckRunAppTokenSteps(data *WorkflowData) []string {
	if data.SafeOutputs == nil || data.SafeOutputs.CreateCheckRun == nil || data.SafeOutputs.CreateCheckRun.GitHubApp == nil {
		return nil
	}
	consolidatedSafeOutputsStepsLog.Print("Adding per-handler GitHub App token minting step for create-check-run")
	permissions := NewPermissionsContentsReadChecksWrite()
	var steps []string
	for _, step := range c.buildGitHubAppTokenMintStep(data.SafeOutputs.CreateCheckRun.GitHubApp, permissions, "") {
		steps = append(steps, replaceStepID(step, "safe-outputs-app-token", "create-check-run-app-token"))
	}
	return steps
}

func buildHandlerManagerStepHeader(data *WorkflowData) []string {
	return []string{
		"      - name: Process Safe Outputs\n",
		"        id: process_safe_outputs\n",
		fmt.Sprintf("        uses: %s\n", getCachedActionPin("actions/github-script", data)),
		"        env:\n",
		"          GH_AW_AGENT_OUTPUT: ${{ steps.setup-agent-output-env.outputs.GH_AW_AGENT_OUTPUT }}\n",
		"          GH_AW_COMMENT_ID: ${{ needs.activation.outputs.comment_id }}\n",
	}
}

func (c *Compiler) addHandlerManagerEnv(steps *[]string, data *WorkflowData) error {
	if err := c.addHandlerManagerDomainEnv(steps, data); err != nil {
		return err
	}
	addHandlerManagerBaseEnv(steps, data)
	addHandlerManagerCustomTypeEnv(steps, data)
	c.addCustomSafeOutputEnvVars(steps, data)
	c.addHandlerManagerConfigEnvVar(steps, data)
	c.addAllSafeOutputConfigEnvVars(steps, data)
	addHandlerManagerCITokenEnv(steps, data)
	addHandlerManagerProjectEnv(steps, data)
	addHandlerManagerAgentTokenEnv(steps, data)
	addHandlerManagerAgentSessionEnv(steps, data)
	addHandlerManagerGitHubTokenEnv(steps, data)
	return nil
}

func (c *Compiler) addHandlerManagerDomainEnv(steps *[]string, data *WorkflowData) error {
	var domainsStr string
	if data.SafeOutputs != nil && len(data.SafeOutputs.AllowedDomains) > 0 {
		expanded, err := c.computeExpandedAllowedDomainsForSanitization(data)
		if err != nil {
			return err
		}
		domainsStr = expanded
	} else {
		computed, err := c.computeAllowedDomainsForSanitization(data)
		if err != nil {
			return err
		}
		domainsStr = computed
	}
	if domainsStr != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_ALLOWED_DOMAINS: %q\n", domainsStr))
	}
	return nil
}

func addHandlerManagerBaseEnv(steps *[]string, data *WorkflowData) {
	if data.SafeOutputs != nil && data.SafeOutputs.URLs != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_SAFE_OUTPUTS_URLS: %q\n", data.SafeOutputs.URLs))
	}
	*steps = append(*steps, "          GITHUB_SERVER_URL: ${{ github.server_url }}\n")
	*steps = append(*steps, "          GITHUB_API_URL: ${{ github.api_url }}\n")
}

func addHandlerManagerCustomTypeEnv(steps *[]string, data *WorkflowData) {
	if customJobsJSON := buildCustomSafeOutputJobsJSON(data); customJobsJSON != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_SAFE_OUTPUT_JOBS: %q\n", customJobsJSON))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_SAFE_OUTPUT_JOBS env var for custom safe job types")
	}
	if customScriptsJSON := buildCustomSafeOutputScriptsJSON(data); customScriptsJSON != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_SAFE_OUTPUT_SCRIPTS: %q\n", customScriptsJSON))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_SAFE_OUTPUT_SCRIPTS env var for custom script handlers")
	}
	if customActionsJSON := buildCustomSafeOutputActionsJSON(data); customActionsJSON != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_SAFE_OUTPUT_ACTIONS: %q\n", customActionsJSON))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_SAFE_OUTPUT_ACTIONS env var for custom action handlers")
	}
}

func addHandlerManagerCITokenEnv(steps *[]string, data *WorkflowData) {
	if !usesPatchesAndCheckouts(data.SafeOutputs) {
		return
	}
	var ciTriggerToken string
	if data.SafeOutputs.CreatePullRequests != nil && data.SafeOutputs.CreatePullRequests.GithubTokenForExtraEmptyCommit != "" {
		ciTriggerToken = data.SafeOutputs.CreatePullRequests.GithubTokenForExtraEmptyCommit
	} else if data.SafeOutputs.PushToPullRequestBranch != nil && data.SafeOutputs.PushToPullRequestBranch.GithubTokenForExtraEmptyCommit != "" {
		ciTriggerToken = data.SafeOutputs.PushToPullRequestBranch.GithubTokenForExtraEmptyCommit
	}
	if ciTriggerToken == "app" {
		*steps = append(*steps, "          GH_AW_CI_TRIGGER_TOKEN: ${{ steps.safe-outputs-app-token.outputs.token || '' }}\n")
		consolidatedSafeOutputsStepsLog.Print("Extra empty commit using GitHub App token")
		return
	}
	*steps = append(*steps, fmt.Sprintf("          GH_AW_CI_TRIGGER_TOKEN: %s\n", getEffectiveCITriggerGitHubToken(ciTriggerToken)))
	consolidatedSafeOutputsStepsLog.Print("Extra empty commit using GH_AW_CI_TRIGGER_TOKEN")
}

func addHandlerManagerProjectEnv(steps *[]string, data *WorkflowData) {
	projectURL, projectToken := resolveProjectURLAndToken(data.SafeOutputs)
	if projectURL != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_PROJECT_URL: %q\n", projectURL))
	}
	if projectToken != "" {
		*steps = append(*steps, fmt.Sprintf("          GH_AW_PROJECT_GITHUB_TOKEN: %s\n", projectToken))
	}
}

func addHandlerManagerAgentTokenEnv(steps *[]string, data *WorkflowData) {
	if data.SafeOutputs != nil && data.SafeOutputs.AssignToAgent != nil {
		agentTokenStr := getEffectiveCopilotCodingAgentGitHubToken(data.SafeOutputs.AssignToAgent.GitHubToken)
		*steps = append(*steps, fmt.Sprintf("          GH_AW_ASSIGN_TO_AGENT_TOKEN: %s\n", agentTokenStr))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_ASSIGN_TO_AGENT_TOKEN env var for assign-to-agent handler")
	} else if data.SafeOutputs != nil && data.SafeOutputs.CreateIssues != nil && hasCopilotAssignee(data.SafeOutputs.CreateIssues.Assignees) {
		agentTokenStr := getEffectiveCopilotCodingAgentGitHubToken(data.SafeOutputs.CreateIssues.GitHubToken)
		*steps = append(*steps, fmt.Sprintf("          GH_AW_ASSIGN_TO_AGENT_TOKEN: %s\n", agentTokenStr))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_ASSIGN_TO_AGENT_TOKEN env var for create-issue copilot assignment handler")
	} else if data.SafeOutputs != nil && data.SafeOutputs.CreatePullRequests != nil && hasCopilotAssignee(data.SafeOutputs.CreatePullRequests.Assignees) {
		agentTokenStr := getEffectiveCopilotCodingAgentGitHubToken(data.SafeOutputs.CreatePullRequests.GitHubToken)
		*steps = append(*steps, fmt.Sprintf("          GH_AW_ASSIGN_TO_AGENT_TOKEN: %s\n", agentTokenStr))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_ASSIGN_TO_AGENT_TOKEN env var for create-pull-request copilot assignment handler")
	}
}

func addHandlerManagerAgentSessionEnv(steps *[]string, data *WorkflowData) {
	if data.SafeOutputs != nil && data.SafeOutputs.CreateAgentSessions != nil {
		agentSessionTokenStr := getEffectiveCopilotCodingAgentGitHubToken(data.SafeOutputs.CreateAgentSessions.GitHubToken)
		*steps = append(*steps, fmt.Sprintf("          GH_AW_AGENT_SESSION_TOKEN: %s\n", agentSessionTokenStr))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_AGENT_SESSION_TOKEN env var for create-agent-session handler")
	}
}

func addHandlerManagerGitHubTokenEnv(steps *[]string, data *WorkflowData) {
	if !usesPatchesAndCheckouts(data.SafeOutputs) {
		return
	}
	gitToken, isCustom := resolvePRCheckoutToken(data.SafeOutputs, NewCheckoutManager(data.CheckoutConfigs))
	if isCustom {
		*steps = append(*steps, fmt.Sprintf("          GITHUB_TOKEN: %s\n", gitToken))
		consolidatedSafeOutputsStepsLog.Printf("Adding GITHUB_TOKEN env var for cross-repo git CLI operations")
	}
}

func buildHandlerManagerScriptLines() []string {
	return []string{
		"          script: |\n",
		"            const { setupGlobals } = require('" + SetupActionDestination + "/setup_globals.cjs');\n",
		"            setupGlobals(core, github, context, exec, io, getOctokit);\n",
		"            const { main } = require('" + SetupActionDestination + "/safe_output_handler_manager.cjs');\n",
		"            await main();\n",
	}
}

// replaceStepID replaces all occurrences of oldID with newID in a YAML step string.
// Used to generate per-handler token steps from the generic safe-outputs-app-token template.
func replaceStepID(step, oldID, newID string) string {
	return strings.ReplaceAll(step, oldID, newID)
}
