package workflow

import (
	"fmt"
	"sort"

	"github.com/github/gh-aw/pkg/logger"
)

var consolidatedSafeOutputsStepsLog = logger.New("workflow:compiler_safe_outputs_steps")

// buildSharedPRCheckoutSteps builds checkout and git-configuration steps for the
// safe_outputs job's create-pull-request / push-to-pull-request-branch operations.
//
// The checkout steps are generated by the SAME CheckoutManager generators the agent job
// uses (GenerateCheckoutAppTokenSteps, GenerateDefaultCheckoutStep,
// GenerateAdditionalCheckoutSteps), so the safe_outputs job lays out every repository on
// disk identically to the agent job. The only safe_outputs-specific differences are:
//   - a per-step `if:` condition gating the steps on whether a create_pull_request /
//     push_to_pull_request_branch output will actually be processed, and
//   - a trailing "Configure Git credentials" step that installs a push-capable token
//     (the agent job never pushes, so it omits this).
//
// Base-branch selection is intentionally NOT done here. The JS handler resolves the base
// branch per target repository at apply time (it runs `git fetch origin <base>` and
// branches from `origin/<base>` in the target repo's directory), so a checkout-time base
// ref is unnecessary. This is the same mechanism the multi-repo path already relied on.
func (c *Compiler) buildSharedPRCheckoutSteps(data *WorkflowData) []string {
	consolidatedSafeOutputsStepsLog.Print("Building shared PR checkout steps (mirroring agent job layout)")

	// Build the same CheckoutManager the agent job builds from the workflow's checkout: config.
	checkoutMgr := NewCheckoutManager(data.CheckoutConfigs)

	// Unlike the agent job, the safe_outputs job performs git fetch/push against the
	// checked-out repositories (create_pull_request, push_to_pull_request_branch), so its
	// checkouts must retain credentials (persist-credentials: true) instead of stripping
	// them. This keeps the push-capable token on disk for the handlers; the trusted
	// safe_outputs handler code (not the untrusted agent) is the only consumer.
	checkoutMgr.SetKeepCredentialsForPush(true)

	// Persist the resolved PR push token (not just the default GITHUB_TOKEN) into
	// .git/config so the retained credential matches the token the handlers use to
	// fetch/push. This keeps a single, correct Authorization header on the wire and
	// removes the need for the handlers to inject a separate http.extraheader. The
	// same token is reused below for the "Configure Git credentials" step so both the
	// persisted checkout credential and the push remote agree on a single token.
	prCheckoutToken, _ := resolvePRCheckoutToken(data.SafeOutputs, checkoutMgr)
	checkoutMgr.SetPushToken(resolveStaticCheckoutToken(data.SafeOutputs, checkoutMgr))

	// Combined condition: run the checkout/git-config steps only when a create_pull_request
	// or push_to_pull_request_branch output will be processed.
	condition := buildPRCheckoutCondition(data.SafeOutputs)

	var steps []string

	// Mint checkout app tokens (identical to the agent job) when any checkout uses app auth.
	// These must live in the safe_outputs job because the minted token is referenced by the
	// checkout steps via ${{ steps.checkout-app-token-N.outputs.token }} within the same job.
	if checkoutMgr.HasAppAuth() {
		steps = append(steps, injectStepCondition(checkoutMgr.GenerateCheckoutAppTokenSteps(c, resolveCheckoutPermissions(data)), condition)...)
	}
	if checkoutMgr.HasSafeOutputAppAuth() {
		steps = append(steps, checkoutMgr.GenerateSafeOutputCheckoutAppTokenSteps(c, resolveCheckoutPermissions(data))...)
	}

	// Default workspace checkout (identical to the agent job).
	steps = append(steps, injectStepCondition(
		checkoutMgr.GenerateDefaultCheckoutStep(c.trialMode, c.trialLogicalRepoSlug, c.getActionPin),
		condition,
	)...)

	// Additional (cross-repo / subdirectory) checkouts (identical to the agent job).
	steps = append(steps, injectStepCondition(
		checkoutMgr.GenerateAdditionalCheckoutSteps(c.getActionPin),
		condition,
	)...)

	// Configure Git credentials so the safe_outputs job can push. The agent job never
	// pushes, so this step has no agent-job equivalent. Reuse the token resolved above so
	// the push remote and the persisted checkout credential use the same token.
	steps = append(steps, checkoutMgr.GenerateConfigureGitCredentialsSteps(prCheckoutToken, condition)...)

	consolidatedSafeOutputsStepsLog.Printf("Built shared PR checkout steps with condition: %s", condition.Render())
	return steps
}

// buildHandlerManagerStep builds a single step that uses the safe output handler manager
// to dispatch messages to appropriate handlers. This replaces multiple individual steps
// with a single dispatcher step that processes all safe output types.
func (c *Compiler) buildHandlerManagerStep(data *WorkflowData) ([]string, error) {
	consolidatedSafeOutputsStepsLog.Print("Building handler manager step")
	steps := c.buildHandlerManagerTokenMintingSteps(data)
	steps = append(steps,
		"      - name: Process Safe Outputs\n",
		"        id: process_safe_outputs\n",
		fmt.Sprintf("        uses: %s\n", getCachedActionPin("actions/github-script", data)),
		"        env:\n",
		"          GH_AW_AGENT_OUTPUT: ${{ steps.setup-agent-output-env.outputs.GH_AW_AGENT_OUTPUT }}\n",
		"          GH_AW_COMMENT_ID: ${{ needs.activation.outputs.comment_id }}\n",
	)
	var err error
	steps, err = c.appendHandlerManagerEnvSection(steps, data)
	if err != nil {
		return nil, err
	}
	steps = append(steps, "        with:\n")
	configToken := ""
	if data.SafeOutputs != nil && data.SafeOutputs.GitHubToken != "" {
		configToken = data.SafeOutputs.GitHubToken
	}
	c.addSafeOutputGitHubTokenForConfig(&steps, data, configToken)
	steps = append(steps, "          script: |\n", generateGitHubScriptWithRequire("process_safe_outputs.cjs"))
	return steps, nil
}

func (c *Compiler) buildHandlerManagerTokenMintingSteps(data *WorkflowData) []string {
	if data.SafeOutputs == nil {
		return nil
	}
	steps := c.buildPerHandlerAppTokenSteps(data.SafeOutputs)
	return append(steps, c.buildDispatchRepositoryTokenSteps(data.SafeOutputs)...)
}

func (c *Compiler) buildPerHandlerAppTokenSteps(safeOutputs *SafeOutputsConfig) []string {
	var steps []string
	for _, handler := range safeOutputHandlers {
		if handler.StructField == "" {
			continue
		}
		handlerApp := getHandlerGitHubApp(safeOutputs, handler.StructField)
		if handlerApp == nil || handler.PermissionBuilder == nil {
			continue
		}
		handlerPermissions := handler.PermissionBuilder(safeOutputs)
		if handlerPermissions == nil {
			continue
		}
		stepID := handler.Key + "-app-token"
		consolidatedSafeOutputsStepsLog.Printf("Adding per-handler GitHub App token minting step for %s", handler.Key)
		steps = append(steps, c.buildGitHubAppTokenMintStepWithMeta(handlerApp, handlerPermissions, "", "", fmt.Sprintf("Generate GitHub App token (%s)", handler.Key), stepID)...)
	}
	return steps
}

func (c *Compiler) buildDispatchRepositoryTokenSteps(safeOutputs *SafeOutputsConfig) []string {
	if safeOutputs.DispatchRepository == nil || len(safeOutputs.DispatchRepository.Tools) == 0 {
		return nil
	}
	toolKeys := make([]string, 0, len(safeOutputs.DispatchRepository.Tools))
	for toolKey := range safeOutputs.DispatchRepository.Tools {
		toolKeys = append(toolKeys, toolKey)
	}
	sort.Strings(toolKeys)
	globalStaged := templatableBoolIsTrue(safeOutputs.Staged)
	var steps []string
	for _, toolKey := range toolKeys {
		tool := safeOutputs.DispatchRepository.Tools[toolKey]
		if tool == nil || tool.GitHubApp == nil || isHandlerStaged(globalStaged, tool.Staged) {
			continue
		}
		stepID := dispatchRepositoryToolAppTokenStepID(toolKey)
		consolidatedSafeOutputsStepsLog.Printf("Adding dispatch-repository GitHub App token minting step for %s", toolKey)
		steps = append(steps, c.buildGitHubAppTokenMintStepWithMeta(tool.GitHubApp, NewPermissionsContentsWrite(), "", "", fmt.Sprintf("Generate GitHub App token (dispatch-repository %s)", toolKey), stepID)...)
	}
	return steps
}

func (c *Compiler) appendHandlerManagerEnvSection(steps []string, data *WorkflowData) ([]string, error) {
	domainsStr, err := c.resolveHandlerManagerAllowedDomains(data)
	if err != nil {
		return nil, err
	}
	steps = appendHandlerManagerBaseEnv(steps, data, domainsStr)
	c.addCustomSafeOutputEnvVars(&steps, data)
	c.addHandlerManagerConfigEnvVar(&steps, data)
	c.addAllSafeOutputConfigEnvVars(&steps, data)
	return c.appendHandlerManagerTokenEnv(steps, data), nil
}

func (c *Compiler) resolveHandlerManagerAllowedDomains(data *WorkflowData) (string, error) {
	if data.SafeOutputs != nil && len(data.SafeOutputs.AllowedDomains) > 0 {
		return c.computeExpandedAllowedDomainsForSanitization(data)
	}
	return c.computeAllowedDomainsForSanitization(data)
}

func appendHandlerManagerBaseEnv(steps []string, data *WorkflowData, domainsStr string) []string {
	if domainsStr != "" {
		steps = append(steps, fmt.Sprintf("          GH_AW_ALLOWED_DOMAINS: %q\n", domainsStr))
	}
	if data.SafeOutputs != nil && data.SafeOutputs.URLs != "" {
		steps = append(steps, fmt.Sprintf("          GH_AW_SAFE_OUTPUTS_URLS: %q\n", data.SafeOutputs.URLs))
	}
	steps = append(steps, "          GITHUB_SERVER_URL: ${{ github.server_url }}\n", "          GITHUB_API_URL: ${{ github.api_url }}\n")
	for _, entry := range []struct{ key, value, log string }{
		{"GH_AW_SAFE_OUTPUT_JOBS", buildCustomSafeOutputJobsJSON(data), "Added GH_AW_SAFE_OUTPUT_JOBS env var for custom safe job types"},
		{"GH_AW_SAFE_OUTPUT_SCRIPTS", buildCustomSafeOutputScriptsJSON(data), "Added GH_AW_SAFE_OUTPUT_SCRIPTS env var for custom script handlers"},
		{"GH_AW_SAFE_OUTPUT_ACTIONS", buildCustomSafeOutputActionsJSON(data), "Added GH_AW_SAFE_OUTPUT_ACTIONS env var for custom action handlers"},
	} {
		if entry.value == "" {
			continue
		}
		steps = append(steps, fmt.Sprintf("          %s: %q\n", entry.key, entry.value))
		consolidatedSafeOutputsStepsLog.Print(entry.log)
	}
	return steps
}

func (c *Compiler) appendHandlerManagerTokenEnv(steps []string, data *WorkflowData) []string {
	steps = appendHandlerManagerCITriggerEnv(steps, data)
	steps = appendHandlerManagerProjectEnv(steps, data.SafeOutputs)
	steps = appendHandlerManagerAssignmentEnv(steps, data.SafeOutputs)
	steps = appendHandlerManagerAgentSessionEnv(steps, data.SafeOutputs)
	return appendHandlerManagerGitTokenEnv(steps, data)
}

func appendHandlerManagerCITriggerEnv(steps []string, data *WorkflowData) []string {
	if !usesPatchesAndCheckouts(data.SafeOutputs) {
		return steps
	}
	ciTriggerToken := ""
	if data.SafeOutputs.CreatePullRequests != nil && data.SafeOutputs.CreatePullRequests.GithubTokenForExtraEmptyCommit != "" {
		ciTriggerToken = data.SafeOutputs.CreatePullRequests.GithubTokenForExtraEmptyCommit
	} else if data.SafeOutputs.PushToPullRequestBranch != nil && data.SafeOutputs.PushToPullRequestBranch.GithubTokenForExtraEmptyCommit != "" {
		ciTriggerToken = data.SafeOutputs.PushToPullRequestBranch.GithubTokenForExtraEmptyCommit
	}
	if ciTriggerToken == "app" {
		consolidatedSafeOutputsStepsLog.Print("Extra empty commit using GitHub App token")
		return append(steps, "          GH_AW_CI_TRIGGER_TOKEN: ${{ steps.safe-outputs-app-token.outputs.token || '' }}\n")
	}
	consolidatedSafeOutputsStepsLog.Print("Extra empty commit using GH_AW_CI_TRIGGER_TOKEN")
	return append(steps, fmt.Sprintf("          GH_AW_CI_TRIGGER_TOKEN: %s\n", getEffectiveCITriggerGitHubToken(ciTriggerToken)))
}

func appendHandlerManagerProjectEnv(steps []string, safeOutputs *SafeOutputsConfig) []string {
	projectURL, projectToken := resolveProjectURLAndToken(safeOutputs)
	if projectURL != "" {
		steps = append(steps, fmt.Sprintf("          GH_AW_PROJECT_URL: %q\n", projectURL))
	}
	if projectToken != "" {
		steps = append(steps, fmt.Sprintf("          GH_AW_PROJECT_GITHUB_TOKEN: %s\n", projectToken))
	}
	return steps
}

func appendHandlerManagerAssignmentEnv(steps []string, safeOutputs *SafeOutputsConfig) []string {
	switch {
	case safeOutputs != nil && safeOutputs.AssignToAgent != nil:
		steps = append(steps, fmt.Sprintf("          GH_AW_ASSIGN_TO_AGENT_TOKEN: %s\n", getEffectiveCopilotCodingAgentGitHubToken(safeOutputs.AssignToAgent.GitHubToken)))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_ASSIGN_TO_AGENT_TOKEN env var for assign-to-agent handler")
	case safeOutputs != nil && safeOutputs.CreateIssues != nil && hasCopilotAssignee(safeOutputs.CreateIssues.Assignees):
		steps = append(steps, fmt.Sprintf("          GH_AW_ASSIGN_TO_AGENT_TOKEN: %s\n", getEffectiveCopilotCodingAgentGitHubToken(safeOutputs.CreateIssues.GitHubToken)))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_ASSIGN_TO_AGENT_TOKEN env var for create-issue copilot assignment handler")
	case safeOutputs != nil && safeOutputs.CreatePullRequests != nil && hasCopilotAssignee(safeOutputs.CreatePullRequests.Assignees):
		steps = append(steps, fmt.Sprintf("          GH_AW_ASSIGN_TO_AGENT_TOKEN: %s\n", getEffectiveCopilotCodingAgentGitHubToken(safeOutputs.CreatePullRequests.GitHubToken)))
		consolidatedSafeOutputsStepsLog.Print("Added GH_AW_ASSIGN_TO_AGENT_TOKEN env var for create-pull-request copilot assignment handler")
	}
	return steps
}

func appendHandlerManagerAgentSessionEnv(steps []string, safeOutputs *SafeOutputsConfig) []string {
	if safeOutputs == nil || safeOutputs.CreateAgentSessions == nil {
		return steps
	}
	steps = append(steps, fmt.Sprintf("          GH_AW_AGENT_SESSION_TOKEN: %s\n", getEffectiveCopilotCodingAgentGitHubToken(safeOutputs.CreateAgentSessions.GitHubToken)))
	consolidatedSafeOutputsStepsLog.Print("Added GH_AW_AGENT_SESSION_TOKEN env var for create-agent-session handler")
	return steps
}

func appendHandlerManagerGitTokenEnv(steps []string, data *WorkflowData) []string {
	if !usesPatchesAndCheckouts(data.SafeOutputs) {
		return steps
	}
	gitToken, isCustom := resolvePRCheckoutToken(data.SafeOutputs, NewCheckoutManager(data.CheckoutConfigs))
	if !isCustom {
		return steps
	}
	consolidatedSafeOutputsStepsLog.Printf("Adding GITHUB_TOKEN env var for cross-repo git CLI operations")
	return append(steps, fmt.Sprintf("          GITHUB_TOKEN: %s\n", gitToken))
}
