package workflow

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/github/gh-aw/pkg/console"
	"github.com/github/gh-aw/pkg/constants"
)

// validateExpressions checks expression safety and runtime-import file references
// embedded in the workflow's markdown content. It is the first validator called in
// validateWorkflowData and guards against unsafe GitHub Actions expressions.
func (c *Compiler) validateExpressions(workflowData *WorkflowData, markdownPath string) error {
	// Validate expression safety - check that all GitHub Actions expressions are in the allowed list
	if strings.Contains(workflowData.MarkdownContent, "${{") {
		workflowLog.Printf("Validating expression safety")
		if err := validateExpressionSafety(workflowData.MarkdownContent); err != nil {
			return formatCompilerError(markdownPath, "error", err.Error(), err)
		}
	}

	// Validate expressions in runtime-import files at compile time
	if strings.Contains(workflowData.MarkdownContent, "{{#runtime-import") {
		workflowLog.Printf("Validating runtime-import files")
		// Go up from .github/workflows/file.md to repo root
		workflowDir := filepath.Dir(markdownPath) // .github/workflows
		githubDir := filepath.Dir(workflowDir)    // .github
		workspaceDir := filepath.Dir(githubDir)   // repo root
		subAgentWarnings, err := validateRuntimeImportFiles(workflowData.MarkdownContent, workspaceDir)
		// Emit best-effort sub-agent frontmatter warnings through the normal warning path
		// so they are counted and consistently formatted with all other warnings.
		for _, w := range subAgentWarnings {
			expressionValidationLog.Printf("%s", w)
			fmt.Fprintln(os.Stderr, console.FormatWarningMessage(w))
			c.IncrementWarningCount()
		}
		if err != nil {
			return formatCompilerError(markdownPath, "error", err.Error(), err)
		}
	}

	// Warn when the prompt explicitly references /tmp/ or /tmp/gh-aw/ directly instead
	// of the recommended /tmp/gh-aw/agent/ subtree.
	c.validatePromptTmpPaths(workflowData, markdownPath)

	return nil
}

// tmpNeedle is the literal prefix to scan for in prompt content.
const tmpNeedle = "/tmp/"

// tmpSafePrefix is the /tmp subtree managed by the gh-aw framework.
// All paths under /tmp/gh-aw/ are considered safe (agent output, cache-memory,
// repo-memory, comment-memory, aw-mcp, mcp-scripts, etc.).
const tmpSafePrefix = "/tmp/gh-aw/"

// warnPromptTmpPaths returns a non-empty advisory message when content contains
// /tmp/ references that are not under /tmp/gh-aw/.
// Returns an empty string when no problematic patterns are found.
func warnPromptTmpPaths(content string) string {
	if !strings.Contains(content, tmpNeedle) {
		return ""
	}
	// Walk every /tmp/ occurrence; warn as soon as one is not under /tmp/gh-aw/.
	rest := content
	for {
		pos := strings.Index(rest, tmpNeedle)
		if pos < 0 {
			break
		}
		segment := rest[pos:]
		if !strings.HasPrefix(segment, tmpSafePrefix) {
			return "Prompt references /tmp/ directly. " +
				"Use /tmp/gh-aw/agent/ as the root for all temporary files " +
				"generated by the agent — its contents are uploaded as a run artifact."
		}
		rest = rest[pos+len(tmpNeedle):]
	}
	return ""
}

// validatePromptTmpPaths emits an advisory warning when the workflow markdown body
// references /tmp/ or /tmp/gh-aw/ instead of the recommended /tmp/gh-aw/agent/ root.
func (c *Compiler) validatePromptTmpPaths(workflowData *WorkflowData, markdownPath string) {
	if msg := warnPromptTmpPaths(workflowData.MarkdownContent); msg != "" {
		fmt.Fprintln(os.Stderr, formatCompilerMessage(markdownPath, "warning", msg))
		c.IncrementWarningCount()
	}
}

// validateFeatureConfig validates feature flags declared in the workflow frontmatter
// and applies any action-mode override specified via the "action-mode" feature flag.
func (c *Compiler) validateFeatureConfig(workflowData *WorkflowData, markdownPath string) error {
	// Validate feature flags
	workflowLog.Printf("Validating feature flags")
	if err := validateFeatures(workflowData); err != nil {
		return formatCompilerError(markdownPath, "error", err.Error(), err)
	}

	// Check for action-mode feature flag override
	if workflowData.Features != nil {
		if actionModeVal, exists := workflowData.Features["action-mode"]; exists {
			if actionModeStr, ok := actionModeVal.(string); ok && actionModeStr != "" {
				mode := ActionMode(actionModeStr)
				if !mode.IsValid() {
					return formatCompilerError(markdownPath, "error", fmt.Sprintf("invalid action-mode feature flag '%s'. Must be 'dev', 'release', or 'script'", actionModeStr), nil)
				}
				workflowLog.Printf("Overriding action mode from feature flag: %s", mode)
				c.SetActionMode(mode)
			}
		}
	}

	return nil
}

// validateToolConfiguration validates safe-outputs settings, on.needs and safe-job
// declarations, network configuration, labels, concurrency expressions, sandbox
// security constraints, GitHub tool-to-toolset alignment, the agentic-workflows
// permission requirement, and dispatch/call-workflow configurations.
// workflowPermissions is the *Permissions value returned by validatePermissions.
func (c *Compiler) validateToolConfiguration(workflowData *WorkflowData, markdownPath string, workflowPermissions *Permissions) error {
	workflowLog.Printf("Validating agent file if specified")
	if err := c.validateAgentFile(workflowData, markdownPath); err != nil {
		return err
	}
	if err := c.validateCoreToolConfiguration(workflowData, markdownPath); err != nil {
		return err
	}
	if err := c.validateConcurrencyConfiguration(workflowData, markdownPath); err != nil {
		return err
	}
	c.emitGeneralToolWarnings(workflowData, markdownPath)
	if err := c.validateThreatDetectionSandboxRequirement(workflowData, markdownPath); err != nil {
		return err
	}
	if err := c.validateGitHubToolsAndPermissions(workflowData, markdownPath, workflowPermissions); err != nil {
		return err
	}
	return c.validateResourcesAndDispatches(workflowData, markdownPath)
}

func (c *Compiler) validateCoreToolConfiguration(workflowData *WorkflowData, markdownPath string) error {
	validations := []struct {
		logMessage string
		validateFn func() error
	}{
		{logMessage: "Validating sandbox configuration", validateFn: func() error { return validateSandboxConfig(workflowData) }},
		{logMessage: "Validating safe-outputs target fields", validateFn: func() error { return validateSafeOutputsTarget(workflowData.SafeOutputs) }},
		{logMessage: "Validating safe-outputs max fields", validateFn: func() error { return validateSafeOutputsMax(workflowData.SafeOutputs) }},
		{logMessage: "Validating safe-outputs samples entries against MCP tool schemas", validateFn: func() error { return validateSafeOutputsSamples(workflowData.SafeOutputs) }},
		{logMessage: "Validating safe-outputs urls policy", validateFn: func() error { return validateSafeOutputsURLs(workflowData.SafeOutputs) }},
		{logMessage: "Validating safe-outputs allowed-domains", validateFn: func() error { return c.validateSafeOutputsAllowedDomains(workflowData.SafeOutputs) }},
		{logMessage: "Validating safe-outputs merge-pull-request", validateFn: func() error { return validateSafeOutputsMergePullRequest(workflowData.SafeOutputs) }},
		{logMessage: "Validating safe-outputs needs declarations", validateFn: func() error { return validateSafeOutputsNeeds(workflowData) }},
		{logMessage: "Validating on.needs declarations", validateFn: func() error { return c.validateOnNeeds(workflowData) }},
		{logMessage: "Validating safe-job needs declarations", validateFn: func() error { return validateSafeJobNeeds(workflowData) }},
		{logMessage: "Validating safe-outputs allowed-labels glob scope", validateFn: func() error { return c.validateSafeOutputsAllowedLabelsGlobScope(workflowData.SafeOutputs) }},
		{logMessage: "Validating network allowed domains", validateFn: func() error { return c.validateNetworkAllowedDomains(workflowData.NetworkPermissions) }},
		{logMessage: "Validating network firewall configuration", validateFn: func() error { return validateNetworkFirewallConfig(workflowData.NetworkPermissions) }},
		{logMessage: "Validating safe-outputs allow-workflows", validateFn: func() error { return validateSafeOutputsAllowWorkflows(workflowData.SafeOutputs) }},
		{logMessage: "Validating OTLP resource attributes", validateFn: func() error { return validateOTLPResourceAttributes(workflowData) }},
		{logMessage: "Validating labels", validateFn: func() error { return validateLabels(workflowData) }},
		{logMessage: "Validating workflow_dispatch input requirements for command triggers", validateFn: func() error { return validateCommandWorkflowDispatchInputs(workflowData) }},
		{logMessage: "Validating max-daily-ai-credits frontmatter", validateFn: func() error { return validateMaxDailyAICFrontmatter(workflowData) }},
	}
	// This validation is intentionally outside the table below because strict mode
	// turns the same validation result into either an error or a warning.
	workflowLog.Printf("Validating safe-outputs steps for shell expansion patterns")
	if err := validateSafeOutputsStepsShellExpansion(workflowData.SafeOutputs); err != nil {
		if c.strictMode {
			return formatCompilerError(markdownPath, "error", err.Error(), err)
		}
		fmt.Fprintln(os.Stderr, formatCompilerMessage(markdownPath, "warning", err.Error()))
		c.IncrementWarningCount()
	}
	workflowLog.Printf("Validating push-to-pull-request-branch configuration")
	c.validatePushToPullRequestBranchWarnings(workflowData.SafeOutputs, workflowData.CheckoutConfigs)
	for _, validation := range validations {
		workflowLog.Printf("%s", validation.logMessage)
		if err := validation.validateFn(); err != nil {
			return formatCompilerError(markdownPath, "error", err.Error(), err)
		}
	}
	return nil
}

func (c *Compiler) validateThreatDetectionSandboxRequirement(workflowData *WorkflowData, markdownPath string) error {
	if workflowData.SafeOutputs != nil && workflowData.SafeOutputs.ThreatDetection != nil && isAgentSandboxDisabled(workflowData) {
		return formatCompilerError(markdownPath, "error", "threat detection requires sandbox.agent to be enabled. Threat detection runs inside the agent sandbox (AWF) with fully blocked network. Either enable sandbox.agent or use 'threat-detection: false' to disable the threat-detection configuration in safe-outputs.", errors.New("threat detection requires sandbox.agent"))
	}
	return nil
}

func (c *Compiler) validateConcurrencyConfiguration(workflowData *WorkflowData, markdownPath string) error {
	workflowLog.Printf("Validating workflow-level concurrency configuration")
	if err := validateWorkflowConcurrency(workflowData, markdownPath); err != nil {
		return err
	}
	if workflowData.ConcurrencyJobDiscriminator != "" {
		if err := validateConcurrencyGroupExpression(workflowData.ConcurrencyJobDiscriminator); err != nil {
			return formatCompilerError(markdownPath, "error", "concurrency.job-discriminator validation failed: "+err.Error(), err)
		}
	}
	workflowLog.Printf("Validating engine-level concurrency configuration")
	if workflowData.EngineConfig != nil && workflowData.EngineConfig.Concurrency != "" {
		if err := validateConcurrencyQueueConfiguration(workflowData.EngineConfig.Concurrency); err != nil {
			return formatCompilerError(markdownPath, "error", "engine.concurrency validation failed: "+err.Error(), err)
		}
		groupExpr := extractConcurrencyGroupFromYAML(workflowData.EngineConfig.Concurrency)
		if groupExpr != "" {
			if err := validateConcurrencyGroupExpression(groupExpr); err != nil {
				return formatCompilerError(markdownPath, "error", "engine.concurrency validation failed: "+err.Error(), err)
			}
		}
	}
	if workflowData.SafeOutputs != nil && workflowData.SafeOutputs.ConcurrencyGroup != "" {
		if err := validateConcurrencyGroupExpression(workflowData.SafeOutputs.ConcurrencyGroup); err != nil {
			return formatCompilerError(markdownPath, "error", "safe-outputs.concurrency-group validation failed: "+err.Error(), err)
		}
	}
	return nil
}

func validateWorkflowConcurrency(workflowData *WorkflowData, markdownPath string) error {
	if workflowData.Concurrency == "" {
		return nil
	}
	if err := validateConcurrencyQueueConfiguration(workflowData.Concurrency); err != nil {
		return formatCompilerError(markdownPath, "error", "workflow-level concurrency validation failed: "+err.Error(), err)
	}
	if workflowData.CachedConcurrencyGroupExprSet {
		if workflowData.CachedConcurrencyGroupExprErr != nil {
			return formatCompilerError(markdownPath, "error", "workflow-level concurrency validation failed: "+workflowData.CachedConcurrencyGroupExprErr.Error(), workflowData.CachedConcurrencyGroupExprErr)
		}
		return nil
	}
	groupExpr := extractConcurrencyGroupFromYAML(workflowData.Concurrency)
	if groupExpr == "" {
		return nil
	}
	if err := validateConcurrencyGroupExpression(groupExpr); err != nil {
		return formatCompilerError(markdownPath, "error", "workflow-level concurrency validation failed: "+err.Error(), err)
	}
	return nil
}

func (c *Compiler) emitGeneralToolWarnings(workflowData *WorkflowData, markdownPath string) {
	if workflowData.Concurrency != "" && strings.Contains(workflowData.Concurrency, "cancel-in-progress: true") && hasBotSelfCancelRisk(workflowData) {
		fmt.Fprintln(os.Stderr, formatCompilerMessage(markdownPath, "warning",
			"Custom workflow-level concurrency with cancel-in-progress: true may cause self-cancellation.\n"+
				"safe-outputs.github-app can post comments that re-trigger this workflow via issue_comment,\n"+
				"and those passive bot-authored runs can collide with the primary run's concurrency group.\n"+
				"Add `contains(github.actor, '[bot]') && github.run_id ||` at the start of your concurrency\n"+
				"group expression to route bot-triggered runs to a unique key and prevent self-cancellation.\n"+
				"See: https://gh.io/gh-aw/reference/concurrency for details."))
		c.IncrementWarningCount()
	}
	if isAgentSandboxDisabled(workflowData) {
		fmt.Fprintln(os.Stderr, formatCompilerMessage(markdownPath, "warning",
			"Agent sandbox disabled (sandbox.agent: false). This removes firewall protection. "+
				"The AI agent will have direct network access without firewall filtering. "+
				"The MCP gateway remains enabled. Only use this for testing or in controlled "+
				"environments where you trust the AI agent completely."))
		c.IncrementWarningCount()
	}
	if workflowData.SafeOutputs != nil && workflowData.SafeOutputs.AssignToAgent != nil &&
		workflowData.SafeOutputs.GitHubApp != nil && workflowData.SafeOutputs.AssignToAgent.GitHubToken == "" {
		fmt.Fprintln(os.Stderr, console.FormatWarningMessage(
			"assign-to-agent does not support GitHub App tokens. "+
				"The Copilot assignment API requires a fine-grained PAT. "+
				"The token fallback chain (GH_AW_AGENT_TOKEN || GH_AW_GITHUB_TOKEN || GITHUB_TOKEN) will be used automatically. "+
				"Add github-token: to your assign-to-agent config to specify a different token."))
		c.IncrementWarningCount()
	}
	c.emitExperimentalFeatureWarnings(workflowData)
	if len(workflowData.Command) > 0 && len(workflowData.Bots) > 0 {
		fmt.Fprintln(os.Stderr, formatCompilerMessage(markdownPath, "warning",
			"Both slash_command and bots triggers are configured. If a bot listed in bots: "+
				"posts a comment that starts with the slash command text (e.g., /command-name), "+
				"it will trigger the workflow and occupy the concurrency slot, potentially "+
				"blocking simultaneous manual invocations. To ensure the workflow only runs on "+
				"explicit user commands, remove the 'bots:' field."))
		c.IncrementWarningCount()
	}
	if workflowData.Redirect != "" {
		fmt.Fprintln(os.Stderr, formatCompilerMessage(markdownPath, "info", "workflow redirect configured: updates move to "+workflowData.Redirect))
	}
}

func (c *Compiler) emitExperimentalFeatureWarnings(workflowData *WorkflowData) {
	warnings := []struct {
		enabled bool
		message string
	}{
		{enabled: workflowData.RateLimit != nil, message: "Using experimental feature: rate limiting"},
		{enabled: workflowData.SafeOutputs != nil && workflowData.SafeOutputs.DispatchRepository != nil, message: "Using experimental feature: dispatch-repository"},
		{enabled: workflowData.SafeOutputs != nil && workflowData.SafeOutputs.MergePullRequest != nil, message: "Using experimental feature: merge-pull-request"},
		{enabled: workflowData.SafeOutputs != nil && workflowData.SafeOutputs.ReplaceLabel != nil, message: "Using experimental feature: replace-label"},
		{enabled: workflowData.EngineConfig != nil && workflowData.EngineConfig.CopilotSDK, message: "Using experimental feature: engine.copilot-sdk"},
		{enabled: isFeatureEnabled(constants.GHAWDetectionFeatureFlag, workflowData), message: "Using experimental feature: gh-aw-detection"},
		{enabled: len(workflowData.LSP) > 0, message: "Using experimental feature: lsp"},
	}
	for _, warning := range warnings {
		if warning.enabled {
			fmt.Fprintln(os.Stderr, console.FormatWarningMessage(warning.message))
			c.IncrementWarningCount()
		}
	}
	if shouldWarnSparseInteractionCells(workflowData) {
		fmt.Fprintln(os.Stderr, console.FormatWarningMessage(
			"experiments: potential sparse interaction cells detected (multiple active experiments with weighted traffic). "+
				"Reporting should include factorial K1×K2 cell diagnostics before recommending promotion."))
		c.IncrementWarningCount()
	}
}

func (c *Compiler) validateGitHubToolsAndPermissions(workflowData *WorkflowData, markdownPath string, workflowPermissions *Permissions) error {
	workflowLog.Printf("Validating GitHub tools against enabled toolsets")
	if workflowData.ParsedTools != nil && workflowData.ParsedTools.GitHub != nil {
		allowedTools := workflowData.ParsedTools.GitHub.Allowed.ToStringSlice()
		enabledToolsets := workflowData.CachedParsedToolsets
		if enabledToolsets == nil {
			enabledToolsets = ParseGitHubToolsets(strings.Join(workflowData.ParsedTools.GitHub.Toolset.ToStringSlice(), ","))
		}
		if err := ValidateGitHubToolsAgainstToolsets(allowedTools, enabledToolsets); err != nil {
			return formatCompilerError(markdownPath, "error", err.Error(), err)
		}
		originalToolsets := workflowData.ParsedTools.GitHub.Toolset.ToStringSlice()
		if slices.Contains(originalToolsets, "projects") {
			fmt.Fprintln(os.Stderr, console.FormatInfoMessage("The 'projects' toolset requires additional authentication."))
			fmt.Fprintln(os.Stderr, console.FormatInfoMessage("See: https://github.github.com/gh-aw/reference/auth-projects/"))
		}
	}
	workflowLog.Printf("Validating permissions for agentic-workflows tool")
	if _, hasAgenticWorkflows := workflowData.Tools["agentic-workflows"]; hasAgenticWorkflows {
		actionsLevel, hasActions := workflowPermissions.Get(PermissionActions)
		if !hasActions || actionsLevel == PermissionNone {
			message := "ERROR: Missing required permission for agentic-workflows tool:\n"
			message += "  - actions: read\n\n"
			message += "The agentic-workflows tool requires actions: read permission to access GitHub Actions data.\n\n"
			message += "Suggested fix: Add the following to your workflow frontmatter:\n"
			message += "permissions:\n"
			message += "  actions: read"
			return formatCompilerError(markdownPath, "error", message, nil)
		}
	}
	return nil
}

func (c *Compiler) validateResourcesAndDispatches(workflowData *WorkflowData, markdownPath string) error {
	workflowLog.Printf("Validating resources field")
	if workflowData.ParsedFrontmatter != nil {
		for _, r := range workflowData.ParsedFrontmatter.Resources {
			if strings.Contains(r, "${{") {
				return formatCompilerError(markdownPath, "error",
					fmt.Sprintf("resources entry %q contains GitHub Actions expression syntax (${{) which is not allowed; use static paths only", r), nil)
			}
		}
	}
	dispatchValidators := []struct {
		logMessage string
		errPrefix  string
		validateFn func(*WorkflowData, string) error
	}{
		{logMessage: "Validating dispatch-workflow configuration", errPrefix: "dispatch-workflow validation failed: ", validateFn: c.validateDispatchWorkflow},
		{logMessage: "Validating dispatch_repository configuration", errPrefix: "dispatch_repository validation failed: ", validateFn: c.validateDispatchRepository},
		{logMessage: "Validating call-workflow configuration", errPrefix: "call-workflow validation failed: ", validateFn: c.validateCallWorkflow},
	}
	for _, validator := range dispatchValidators {
		workflowLog.Print(validator.logMessage)
		if err := validator.validateFn(workflowData, markdownPath); err != nil {
			return formatCompilerError(markdownPath, "error", validator.errPrefix+err.Error(), err)
		}
	}
	return nil
}

// shouldWarnSparseInteractionCells reports whether the compiler should emit a
// sparse-cell interaction warning.
func shouldWarnSparseInteractionCells(workflowData *WorkflowData) bool {
	if workflowData == nil || len(workflowData.Experiments) <= 1 {
		return false
	}
	return hasWeightedTrafficExperiment(workflowData.ExperimentConfigs)
}

// hasWeightedTrafficExperiment returns true when any declared experiment config
// includes a well-formed weight vector (same length as variants, at least one value).
func hasWeightedTrafficExperiment(configs map[string]*ExperimentConfig) bool {
	if len(configs) == 0 {
		return false
	}
	for _, cfg := range configs {
		if cfg == nil || len(cfg.Variants) == 0 {
			continue
		}
		if len(cfg.Weight) == len(cfg.Variants) {
			return true
		}
	}
	return false
}
