package workflow

import (
	"fmt"

	"github.com/github/gh-aw/pkg/logger"
)

var createCodeScanningAlertLog = logger.New("workflow:create_code_scanning_alert")

// CreateCodeScanningAlertsConfig holds configuration for creating repository security advisories (SARIF format) from agent output
type CreateCodeScanningAlertsConfig struct {
	BaseSafeOutputConfig `yaml:",inline"`
	Driver               string   `yaml:"driver,omitempty"`        // Driver name for SARIF tool.driver.name field (default: "GitHub Agentic Workflows Security Scanner")
	TargetRepoSlug       string   `yaml:"target-repo,omitempty"`   // Target repository in format "owner/repo" for cross-repository code scanning alert creation
	AllowedRepos         []string `yaml:"allowed-repos,omitempty"` // List of additional repositories in format "owner/repo" that code scanning alerts can be created in
}

// parseCodeScanningAlertsConfig handles create-code-scanning-alert configuration
func (c *Compiler) parseCodeScanningAlertsConfig(outputMap map[string]any) *CreateCodeScanningAlertsConfig {
	if _, exists := outputMap["create-code-scanning-alert"]; !exists {
		return nil
	}

	createCodeScanningAlertLog.Print("Parsing create-code-scanning-alert configuration")
	configData := outputMap["create-code-scanning-alert"]
	securityReportsConfig := &CreateCodeScanningAlertsConfig{}

	if configMap, ok := configData.(map[string]any); ok {
		// Parse driver
		if driver, exists := configMap["driver"]; exists {
			if driverStr, ok := driver.(string); ok {
				securityReportsConfig.Driver = driverStr
				createCodeScanningAlertLog.Printf("Using custom SARIF driver name: %s", driverStr)
			}
		}

		// Parse target-repo
		securityReportsConfig.TargetRepoSlug = parseTargetRepoFromConfig(configMap)
		if securityReportsConfig.TargetRepoSlug != "" {
			createCodeScanningAlertLog.Printf("Target repo for code scanning alerts: %s", securityReportsConfig.TargetRepoSlug)
		}

		// Parse allowed-repos
		securityReportsConfig.AllowedRepos = parseAllowedReposFromConfig(configMap)
		if len(securityReportsConfig.AllowedRepos) > 0 {
			createCodeScanningAlertLog.Printf("Allowed repos for cross-repo alerts: %d configured", len(securityReportsConfig.AllowedRepos))
		}

		// Parse common base fields with default max of 0 (unlimited)
		c.parseBaseSafeOutputConfig(configMap, &securityReportsConfig.BaseSafeOutputConfig, 0)
	} else {
		// If configData is nil or not a map (e.g., "create-code-scanning-alert:" with no value),
		// still set the default max (nil = unlimited)
		createCodeScanningAlertLog.Print("No config map provided, using defaults (unlimited max)")
		securityReportsConfig.Max = nil
	}

	createCodeScanningAlertLog.Printf("Parsed create-code-scanning-alert config: driver=%q, target-repo=%q, allowed-repos=%d",
		securityReportsConfig.Driver, securityReportsConfig.TargetRepoSlug, len(securityReportsConfig.AllowedRepos))
	return securityReportsConfig
}

// buildUploadCodeScanningSARIFStep builds steps to upload the SARIF file generated by the
// create_code_scanning_alert handler to the GitHub Code Scanning API.
//
// The create_code_scanning_alert.cjs handler writes findings to a SARIF file and sets
// the sarif_file step output on the process_safe_outputs step. These steps run after
// process_safe_outputs and upload the SARIF file only when findings were generated
// (i.e., when the sarif_file output is non-empty).
//
// A restore checkout step is included before the upload to reset the workspace to the
// triggering commit (github.sha). This is necessary because the safe_outputs job may
// have checked out a different branch for PR operations (e.g., the base branch), and
// github/codeql-action/upload-sarif requires the HEAD to match the commit being scanned.
// Without this restore, the upload fails with "commit not found".
//
// The restore step uses actions/checkout with the same token and repository settings
// from the checkout manager (user-configured checkout frontmatter), falling back to
// the PR checkout token when no override is present.
func (c *Compiler) buildUploadCodeScanningSARIFStep(data *WorkflowData) []string {
	createCodeScanningAlertLog.Print("Building SARIF upload step for code scanning alerts")
	var steps []string

	// Restore the workspace to the triggering commit using actions/checkout.
	// The checkout manager provides the correct token and repository settings from the
	// user's checkout frontmatter configuration. The safe_outputs job may have checked
	// out a different branch (e.g., when creating a PR), causing "commit not found" errors.
	//
	// Token precedence (via checkout manager then PR checkout fallback):
	//   1. User-configured checkout.github-token (from frontmatter checkout: config)
	//   2. GitHub App token (safe-outputs-app-token, if a GitHub App is configured)
	//   3. PR checkout token (create-pull-request/push-to-pull-request-branch token, or safe-outputs token)
	//   4. Default fallback: GH_AW_GITHUB_TOKEN || GITHUB_TOKEN
	checkoutMgr := NewCheckoutManager(data.CheckoutConfigs)
	restoreToken := c.resolveRestoreCheckoutToken(checkoutMgr, data)
	createCodeScanningAlertLog.Printf("Using restore checkout token for SARIF upload (derived from checkout manager)")

	steps = append(steps, "      - name: Restore checkout to triggering commit for SARIF upload\n")
	steps = append(steps, "        if: steps.process_safe_outputs.outputs.sarif_file != ''\n")
	steps = append(steps, fmt.Sprintf("        uses: %s\n", GetActionPin("actions/checkout")))
	steps = append(steps, "        with:\n")
	steps = append(steps, "          ref: ${{ github.sha }}\n")
	steps = append(steps, fmt.Sprintf("          token: %s\n", restoreToken))
	steps = append(steps, "          persist-credentials: false\n")
	steps = append(steps, "          fetch-depth: 1\n")

	steps = append(steps, "      - name: Upload SARIF to GitHub Code Scanning\n")
	steps = append(steps, "        id: upload_code_scanning_sarif\n")
	// Only run when findings were generated (sarif_file output is set by the handler)
	steps = append(steps, "        if: steps.process_safe_outputs.outputs.sarif_file != ''\n")
	steps = append(steps, fmt.Sprintf("        uses: %s\n", GetActionPin("github/codeql-action/upload-sarif")))
	steps = append(steps, "        with:\n")
	// NOTE: github/codeql-action/upload-sarif uses 'token' as the input name, not 'github-token'
	c.addUploadSARIFToken(&steps, data, data.SafeOutputs.CreateCodeScanningAlerts.GitHubToken)
	steps = append(steps, "          sarif_file: ${{ steps.process_safe_outputs.outputs.sarif_file }}\n")
	// ref and sha ensure the upload is associated with the correct triggering commit,
	// even when the local HEAD has been reset or the runner checked out a different ref.
	steps = append(steps, "          ref: ${{ github.ref }}\n")
	steps = append(steps, "          sha: ${{ github.sha }}\n")
	steps = append(steps, "          wait-for-processing: true\n")

	return steps
}

// addUploadSARIFToken adds the 'token' input for github/codeql-action/upload-sarif.
// This action uses 'token' as the input name (not 'github-token' like other GitHub Actions).
// Uses precedence: config token > safe-outputs global github-token > GH_AW_GITHUB_TOKEN || GITHUB_TOKEN
func (c *Compiler) addUploadSARIFToken(steps *[]string, data *WorkflowData, configToken string) {
	var safeOutputsToken string
	if data.SafeOutputs != nil {
		safeOutputsToken = data.SafeOutputs.GitHubToken
	}

	// If app is configured, use app token
	if data.SafeOutputs != nil && data.SafeOutputs.GitHubApp != nil {
		*steps = append(*steps, "          token: ${{ steps.safe-outputs-app-token.outputs.token }}\n")
		return
	}

	// Choose the first non-empty custom token for precedence
	effectiveCustomToken := configToken
	if effectiveCustomToken == "" {
		effectiveCustomToken = safeOutputsToken
	}

	effectiveToken := getEffectiveSafeOutputGitHubToken(effectiveCustomToken)
	// Log which token source is being used for debugging
	tokenSource := "default (GH_AW_GITHUB_TOKEN || GITHUB_TOKEN)"
	if configToken != "" {
		tokenSource = "per-config github-token"
	} else if safeOutputsToken != "" {
		tokenSource = "safe-outputs github-token"
	}
	createCodeScanningAlertLog.Printf("Using token for SARIF upload from source: %s (upload-sarif uses 'token' not 'github-token')", tokenSource)
	*steps = append(*steps, fmt.Sprintf("          token: %s\n", effectiveToken))
}

// resolveRestoreCheckoutToken returns the GitHub token to use for the pre-SARIF
// restore checkout step. It consults the checkout manager first (user-configured
// checkout frontmatter), then falls back to the PR checkout token chain.
//
// Token precedence:
//  1. GitHub App token minted for safe-outputs (if safe-outputs app is configured)
//  2. User-configured checkout.github-token from the default workspace checkout
//  3. PR checkout token (create-pull-request / push-to-pull-request-branch / safe-outputs token)
//  4. Default: GH_AW_GITHUB_TOKEN || GITHUB_TOKEN
func (c *Compiler) resolveRestoreCheckoutToken(checkoutMgr *CheckoutManager, data *WorkflowData) string {
	// GitHub App for safe-outputs takes highest precedence
	if data.SafeOutputs != nil && data.SafeOutputs.GitHubApp != nil {
		//nolint:gosec // G101: False positive - this is a GitHub Actions expression template placeholder, not a hardcoded credential
		return "${{ steps.safe-outputs-app-token.outputs.token }}"
	}

	// User-configured checkout token from frontmatter (checkout: github-token: ...)
	override := checkoutMgr.GetDefaultCheckoutOverride()
	if override != nil && override.token != "" {
		createCodeScanningAlertLog.Printf("Using checkout manager override token for SARIF restore checkout")
		return getEffectiveSafeOutputGitHubToken(override.token)
	}

	// Fall back to PR checkout token (which itself falls back to safe-outputs token or GITHUB_TOKEN)
	prToken, _ := computeEffectivePRCheckoutToken(data.SafeOutputs)
	return prToken
}
