package workflow

import (
	"fmt"
	"strings"
)

// generateGitPatchUploadStep generates a step that uploads a git patch artifact
// The patch itself is generated by the safe-outputs MCP server when create_pull_request
// or push_to_pull_request_branch tools are called.
func (c *Compiler) generateGitPatchUploadStep(yaml *strings.Builder) {
	yaml.WriteString("      - name: Upload git patch\n")
	yaml.WriteString("        if: always()\n")
	yaml.WriteString(fmt.Sprintf("        uses: %s\n", GetActionPin("actions/upload-artifact")))
	yaml.WriteString("        with:\n")
	yaml.WriteString("          name: aw.patch\n")
	yaml.WriteString("          path: /tmp/gh-aw/aw.patch\n")
	yaml.WriteString("          if-no-files-found: ignore\n")
}
