package workflow

import (
	"strings"
	"testing"
)

func TestSetVersionAndGetVersion(t *testing.T) {
	// Save original version
	originalVersion := compilerVersion
	defer func() { compilerVersion = originalVersion }()

	tests := []struct {
		version string
	}{
		{"1.0.0"},
		{"dev"},
		{"v2.3.4"},
		{""},
	}

	for _, tt := range tests {
		t.Run(tt.version, func(t *testing.T) {
			SetVersion(tt.version)
			if got := GetVersion(); got != tt.version {
				t.Errorf("GetVersion() = %q, want %q", got, tt.version)
			}
		})
	}
}

func TestGenerateWorkflowHeader_VersionInDevBuild(t *testing.T) {
	// Save original version
	originalVersion := compilerVersion
	defer func() { compilerVersion = originalVersion }()

	// Test with dev version - should not include version in header
	SetVersion("dev")
	header := GenerateWorkflowHeader("test.md", "gh-aw", "")

	if strings.Contains(header, "(dev)") {
		t.Error("Expected header to NOT include version for dev builds")
	}
	if !strings.Contains(header, "This file was automatically generated by gh-aw. DO NOT EDIT.") {
		t.Error("Expected header to contain disclaimer without version")
	}
}

func TestGenerateWorkflowHeader_VersionInReleaseBuild(t *testing.T) {
	// Save original version
	originalVersion := compilerVersion
	defer func() { compilerVersion = originalVersion }()

	// Test with release version (proper semver) - should include version in header
	SetVersion("1.0.0")
	header := GenerateWorkflowHeader("test.md", "gh-aw", "")

	if !strings.Contains(header, "This file was automatically generated by gh-aw (1.0.0). DO NOT EDIT.") {
		t.Errorf("Expected header to contain disclaimer with version, got:\n%s", header)
	}
}

func TestGenerateWorkflowHeader_DirtyVersion(t *testing.T) {
	// Save original version
	originalVersion := compilerVersion
	defer func() { compilerVersion = originalVersion }()

	// Test with dirty version (git describe output) - should NOT include version
	// IsReleasedVersion excludes versions containing "dirty"
	SetVersion("c610c2a-dirty")
	header := GenerateWorkflowHeader("test.md", "gh-aw", "")

	if strings.Contains(header, "(c610c2a-dirty)") {
		t.Error("Expected header to NOT include version for dirty builds")
	}
	if !strings.Contains(header, "This file was automatically generated by gh-aw. DO NOT EDIT.") {
		t.Error("Expected header to contain disclaimer without version")
	}
}

func TestGenerateWorkflowHeader_GitHashVersion(t *testing.T) {
	// Save original version
	originalVersion := compilerVersion
	defer func() { compilerVersion = originalVersion }()

	// Test with git hash version - should NOT include version
	// IsReleasedVersion requires proper semver format
	SetVersion("c610c2a")
	header := GenerateWorkflowHeader("test.md", "gh-aw", "")

	if strings.Contains(header, "(c610c2a)") {
		t.Error("Expected header to NOT include version for git hash builds")
	}
	if !strings.Contains(header, "This file was automatically generated by gh-aw. DO NOT EDIT.") {
		t.Error("Expected header to contain disclaimer without version")
	}
}

func TestGenerateWorkflowHeader_EmptyVersion(t *testing.T) {
	// Save original version
	originalVersion := compilerVersion
	defer func() { compilerVersion = originalVersion }()

	// Test with empty version - should not include version in header
	SetVersion("")
	header := GenerateWorkflowHeader("test.md", "gh-aw", "")

	if strings.Contains(header, "()") {
		t.Error("Expected header to NOT include empty parentheses")
	}
	if !strings.Contains(header, "This file was automatically generated by gh-aw. DO NOT EDIT.") {
		t.Error("Expected header to contain disclaimer without version")
	}
}

func TestGenerateWorkflowHeader_NoGeneratedBy(t *testing.T) {
	// Save original version
	originalVersion := compilerVersion
	defer func() { compilerVersion = originalVersion }()

	// Test with empty generatedBy - should use default message
	SetVersion("1.0.0")
	header := GenerateWorkflowHeader("test.md", "", "")

	if !strings.Contains(header, "This file was automatically generated. DO NOT EDIT.") {
		t.Error("Expected header to contain default disclaimer")
	}
	// Should not include version when generatedBy is empty
	if strings.Contains(header, "(1.0.0)") {
		t.Error("Expected header to NOT include version when generatedBy is empty")
	}
}
