package workflow

// Node.js builtin modules that are available in the Node.js runtime.
// These are modules that can be required without being installed via npm.
// Source: https://nodejs.org/api/
//
// This list includes modules available in Node.js 20 LTS and earlier versions.
var nodejsBuiltinModules = map[string]bool{
	// Core modules
	"assert":            true,
	"assert/strict":     true,
	"async_hooks":       true,
	"buffer":            true,
	"child_process":     true,
	"cluster":           true,
	"console":           true,
	"constants":         true,
	"crypto":            true,
	"dgram":             true,
	"diagnostics_channel": true,
	"dns":               true,
	"dns/promises":      true,
	"domain":            true,
	"events":            true,
	"fs":                true,
	"fs/promises":       true,
	"http":              true,
	"http2":             true,
	"https":             true,
	"inspector":         true,
	"module":            true,
	"net":               true,
	"os":                true,
	"path":              true,
	"path/posix":        true,
	"path/win32":        true,
	"perf_hooks":        true,
	"process":           true,
	"punycode":          true,
	"querystring":       true,
	"readline":          true,
	"readline/promises": true,
	"repl":              true,
	"stream":            true,
	"stream/consumers":  true,
	"stream/promises":   true,
	"stream/web":        true,
	"string_decoder":    true,
	"sys":               true,
	"timers":            true,
	"timers/promises":   true,
	"tls":               true,
	"trace_events":      true,
	"tty":               true,
	"url":               true,
	"util":              true,
	"util/types":        true,
	"v8":                true,
	"vm":                true,
	"wasi":              true,
	"worker_threads":    true,
	"zlib":              true,
	
	// Node.js prefixed versions (node:*)
	"node:assert":            true,
	"node:assert/strict":     true,
	"node:async_hooks":       true,
	"node:buffer":            true,
	"node:child_process":     true,
	"node:cluster":           true,
	"node:console":           true,
	"node:constants":         true,
	"node:crypto":            true,
	"node:dgram":             true,
	"node:diagnostics_channel": true,
	"node:dns":               true,
	"node:dns/promises":      true,
	"node:domain":            true,
	"node:events":            true,
	"node:fs":                true,
	"node:fs/promises":       true,
	"node:http":              true,
	"node:http2":             true,
	"node:https":             true,
	"node:inspector":         true,
	"node:module":            true,
	"node:net":               true,
	"node:os":                true,
	"node:path":              true,
	"node:path/posix":        true,
	"node:path/win32":        true,
	"node:perf_hooks":        true,
	"node:process":           true,
	"node:punycode":          true,
	"node:querystring":       true,
	"node:readline":          true,
	"node:readline/promises": true,
	"node:repl":              true,
	"node:stream":            true,
	"node:stream/consumers":  true,
	"node:stream/promises":   true,
	"node:stream/web":        true,
	"node:string_decoder":    true,
	"node:sys":               true,
	"node:timers":            true,
	"node:timers/promises":   true,
	"node:tls":               true,
	"node:trace_events":      true,
	"node:tty":               true,
	"node:url":               true,
	"node:util":              true,
	"node:util/types":        true,
	"node:v8":                true,
	"node:vm":                true,
	"node:wasi":              true,
	"node:worker_threads":    true,
	"node:zlib":              true,
}

// isNodejsBuiltinModule checks if a module name is a Node.js builtin module.
func isNodejsBuiltinModule(moduleName string) bool {
	return nodejsBuiltinModules[moduleName]
}
