name: 🤖 Create an Agentic Workflow
description: Create a new agentic workflow with AI assistance - just provide a name and description
title: "[Workflow] "
labels: ["workflow", "automation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Create an Agentic Workflow
        
        Provide a workflow name and description. The AI generates technical details (triggers, safe outputs, tools).
        
        **Process:**
        1. AI analyzes requirements and generates workflow
        2. PR created with workflow file
        3. Review and merge to activate

  - type: input
    id: workflow_name
    attributes:
      label: Workflow Name
      description: Short, descriptive name (e.g., "Issue Classifier", "PR Reviewer")
      placeholder: My Workflow Name
    validations:
      required: true

  - type: textarea
    id: workflow_description
    attributes:
      label: Workflow Description
      description: |
        What should this workflow do? Be specific. (~125 words recommended)
        
        Examples:
        - "Label issues based on content"
        - "Review PRs for code quality"
        - "Generate weekly activity reports"
      placeholder: |
        Describe what you want automated...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Triggers, schedules, requirements, constraints
      placeholder: |
        Add relevant context...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ### How it works
        
        1. Issue becomes workflow design hub
        2. AI generates workflow with triggers, tools, safe outputs
        3. PR created automatically
        4. Review and merge to activate
