name: 🚀 Start an Agentic Campaign
description: Create a new agentic campaign with AI assistance - just tell us your goal and we'll generate the details
title: "[Agentic Campaign] "
labels: ["campaign", "campaign-tracker"]
body:
  - type: markdown
    attributes:
      value: |
        ## Start an Agentic Campaign
        
        Provide project board URL and campaign goal. The AI generates technical specs, best practices, and governance policies.
        
        **Process:**
        1. AI analyzes goal and generates campaign spec
        2. PR created with spec and orchestrator files
        3. Review and merge to activate

  - type: input
    id: project_url
    attributes:
      label: Project Board URL
      description: URL of your GitHub Project board for tracking this agentic campaign
      placeholder: https://github.com/orgs/your-org/projects/123
    validations:
      required: true

  - type: textarea
    id: campaign_goal
    attributes:
      label: Agentic Campaign Goal
      description: |
        What should this campaign accomplish? Be specific. (~125 words recommended)
        
        Examples:
        - "Migrate services from Node.js 16 to 20"
        - "Fix critical security vulnerabilities"
        - "Refactor legacy auth code"
      placeholder: |
        Describe your campaign goal...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Constraints, deadlines, requirements, prior learnings
      placeholder: |
        Add relevant context...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ### How it works
        
        1. Issue becomes campaign hub
        2. AI generates spec with workflows, governance, metrics
        3. PR created automatically
        4. Review and merge to activate
