name: 🚀 Start an Agentic Campaign
description: Create a new agentic campaign with AI assistance - just tell us your goal and we'll generate the details
title: "[Agentic Campaign] "
labels: ["campaign", "campaign-tracker"]
body:
  - type: markdown
    attributes:
      value: |
        ## Start an Agentic Campaign
        
        **📌 Important: Project Board Assignment**
        
        This campaign must be assigned to a GitHub Project board. You have two options:
        
        **Option A (Recommended):** Create this issue from your project board:
        1. Open your GitHub Project board
        2. Click "Add item" → "Create new issue"
        3. Select this repository and choose this template
        4. The project will be automatically assigned ✅
        
        **Option B:** Create from issues page (assign project before submitting):
        1. Fill out the form below
        2. **Scroll down and use the project selector at the bottom** to assign a project board
        3. Submit the issue
        
        The AI will automatically detect the project board assignment and generate the campaign specification with the correct project URL.
        
        **Process:**
        1. Fill out the campaign goal and context fields below
        2. **Ensure a project board is assigned** (see options above)
        3. Submit the issue
        4. AI analyzes goal and generates campaign spec with project tracking
        5. PR created with spec and orchestrator files
        6. Review and merge to activate

  - type: textarea
    id: campaign_goal
    attributes:
      label: Agentic Campaign Goal
      description: |
        What should this campaign accomplish? Be specific. (~125 words recommended)
        
        Examples:
        - "Migrate services from Node.js 16 to 20"
        - "Fix critical security vulnerabilities"
        - "Refactor legacy auth code"
      placeholder: |
        Describe your campaign goal...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Constraints, deadlines, requirements, prior learnings
      placeholder: |
        Add relevant context...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ### How it works
        
        1. Issue becomes campaign hub
        2. AI generates spec with workflows, governance, metrics
        3. PR created automatically
        4. Review and merge to activate
