name: 🚀 Start an Agentic Campaign
description: Create a new agentic campaign with AI assistance - describe your goal and we'll generate the details and project board
title: "[New Agentic Campaign]"
labels: ["campaign", "campaign-tracker"]
body:
  - type: markdown
    attributes:
      value: |
        **Note:** A project board will be automatically created from the campaign template when you submit this issue.

  - type: textarea
    id: campaign_goal
    attributes:
      label: What should this campaign accomplish?
      placeholder: |
        Examples:
        - Migrate services from Node.js 16 to 20
        - Fix critical security vulnerabilities
        - Refactor legacy auth code
    validations:
      required: true


