name: 🚀 Start an Agentic Campaign
description: Create a new agentic campaign with AI assistance - just tell us your goal and we'll generate the details
title: "[Agentic Campaign] "
labels: ["campaign", "campaign-tracker"]
body:
  - type: markdown
    attributes:
      value: |
        ## Start an Agentic Campaign with AI Assistance
        
        Our AI campaign expert will help you create a comprehensive agentic campaign specification. Just provide:
        1. Your project board URL (for tracking)
        2. A simple description of what you want to achieve
        
        The AI will generate all the technical details, best practices, and governance policies for you.
        
        **What happens next:**
        1. An AI agent analyzes your goal and generates a complete agentic campaign spec
        2. The spec includes recommended workflows, memory paths, approval policies, and more
        3. A pull request is created automatically with the generated files
        4. Review and merge the PR to activate your agentic campaign

  - type: input
    id: project_url
    attributes:
      label: Project Board URL
      description: URL of your GitHub Project board for tracking this agentic campaign
      placeholder: https://github.com/orgs/your-org/projects/123
    validations:
      required: true

  - type: textarea
    id: campaign_goal
    attributes:
      label: Agentic Campaign Goal
      description: |
        What do you want this agentic campaign to accomplish? Be as specific or as high-level as you'd like.
        
        Examples:
        - "Migrate all services from Node.js 16 to Node.js 20"
        - "Fix all critical security vulnerabilities across our repositories"
        - "Refactor legacy authentication code to use our new auth library"
        - "Upgrade React from v17 to v18 in all frontend projects"
      placeholder: |
        Describe your agentic campaign goal...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: |
        Any other information that might be helpful? (constraints, deadlines, specific requirements, prior learnings, etc.)
      placeholder: |
        Add any relevant context...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ### How it works
        
        After submitting:
        1. **This issue becomes your agentic campaign hub** - Track everything here
        2. **AI generates a comprehensive spec** - Including workflows, governance, and metrics
        3. **A PR is created automatically** - Contains agentic campaign spec and orchestrator files
        4. **Review and merge** - Activate your agentic campaign once you're satisfied
        
        The AI will handle all the technical details and best practices for you!
