name: 🚀 Start an Agentic Campaign
description: Create a new agentic campaign with AI assistance - describe your goal and we'll generate the details
title: "[Agentic Campaign]"
labels: ["campaign", "campaign-tracker"]
body:
  - type: markdown
    attributes:
      value: |
        **Project Board Required:** Assign this issue to a GitHub Project for tracking (use project selector below or create from project board).

  - type: textarea
    id: campaign_goal
    attributes:
      label: What should this campaign accomplish?
      placeholder: |
        Examples:
        - Migrate services from Node.js 16 to 20
        - Fix critical security vulnerabilities
        - Refactor legacy auth code
    validations:
      required: true


