package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/githubnext/gh-aw/pkg/campaign"
	"github.com/githubnext/gh-aw/pkg/console"
	"github.com/githubnext/gh-aw/pkg/workflow"
	"gopkg.in/yaml.v3"
)

func renderGeneratedCampaignLauncherMarkdown(data *workflow.WorkflowData, sourceCampaignPath string) string {
	b := &strings.Builder{}
	b.WriteString("---\n")
	if strings.TrimSpace(data.Name) != "" {
		b.WriteString(fmt.Sprintf("name: %q\n", data.Name))
	}
	if strings.TrimSpace(data.Description) != "" {
		b.WriteString(fmt.Sprintf("description: %q\n", data.Description))
	}
	if strings.TrimSpace(data.On) != "" {
		b.WriteString(strings.TrimSuffix(data.On, "\n"))
		b.WriteString("\n")
	}
	if strings.TrimSpace(data.Concurrency) != "" {
		b.WriteString(strings.TrimSuffix(data.Concurrency, "\n"))
		b.WriteString("\n")
	}

	// Make the launcher runnable by default.
	b.WriteString("engine: copilot\n")

	if data.SafeOutputs != nil {
		outputs := map[string]any{}
		if data.SafeOutputs.AddComments != nil {
			outputs["add-comment"] = map[string]any{"max": data.SafeOutputs.AddComments.Max}
		}
		if data.SafeOutputs.UpdateProjects != nil {
			updateProjectConfig := map[string]any{"max": data.SafeOutputs.UpdateProjects.Max}
			if strings.TrimSpace(data.SafeOutputs.UpdateProjects.GitHubToken) != "" {
				updateProjectConfig["github-token"] = data.SafeOutputs.UpdateProjects.GitHubToken
			}
			outputs["update-project"] = updateProjectConfig
		}
		if len(outputs) > 0 {
			payload := map[string]any{"safe-outputs": outputs}
			if out, err := yaml.Marshal(payload); err == nil {
				b.WriteString(string(out))
			}
		}
	}

	if strings.TrimSpace(data.RunsOn) != "" {
		b.WriteString(strings.TrimSuffix(data.RunsOn, "\n"))
		b.WriteString("\n")
	}
	if len(data.Roles) > 0 {
		b.WriteString("roles:\n")
		for _, role := range data.Roles {
			if strings.TrimSpace(role) == "" {
				continue
			}
			b.WriteString(fmt.Sprintf("  - %q\n", role))
		}
	}
	b.WriteString("---\n\n")
	b.WriteString("<!-- This file was automatically generated by gh-aw. DO NOT EDIT. -->\n")
	if strings.TrimSpace(sourceCampaignPath) != "" {
		relativePath := ToGitRootRelativePath(sourceCampaignPath)
		b.WriteString(fmt.Sprintf("<!-- Source: %s -->\n", relativePath))
	}
	b.WriteString("\n")
	b.WriteString(strings.TrimSpace(data.MarkdownContent))
	b.WriteString("\n")
	return b.String()
}

func generateAndCompileCampaignLauncher(
	compiler *workflow.Compiler,
	spec *campaign.CampaignSpec,
	campaignSpecPath string,
	verbose bool,
	noEmit bool,
	runZizmorPerFile bool,
	runPoutinePerFile bool,
	runActionlintPerFile bool,
	strict bool,
	validateActionSHAs bool,
) (string, error) {
	data, launcherPath := campaign.BuildLauncher(spec, campaignSpecPath)
	if data == nil || launcherPath == "" {
		return "", nil
	}

	if strings.TrimSpace(data.AI) == "" {
		data.AI = "copilot"
	}

	if !noEmit {
		content := renderGeneratedCampaignLauncherMarkdown(data, campaignSpecPath)
		if err := os.WriteFile(launcherPath, []byte(content), 0644); err != nil {
			return "", fmt.Errorf("failed to write generated campaign launcher %s: %w", launcherPath, err)
		}
		if verbose {
			fmt.Fprintln(os.Stderr, console.FormatSuccessMessage(fmt.Sprintf("Generated campaign launcher %s", filepath.Base(launcherPath))))
		}

		if err := CompileWorkflowWithValidation(compiler, launcherPath, verbose, runZizmorPerFile, runPoutinePerFile, runActionlintPerFile, strict, validateActionSHAs); err != nil {
			return launcherPath, err
		}
		return launcherPath, nil
	}

	if err := CompileWorkflowDataWithValidation(compiler, data, launcherPath, verbose, runZizmorPerFile, runPoutinePerFile, runActionlintPerFile, strict, validateActionSHAs); err != nil {
		return launcherPath, err
	}

	return launcherPath, nil
}
