//go:build !integration

package cli

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/github/gh-aw/pkg/gitutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestIssueMonsterWorkflowSupersededGeneratedTaskContract(t *testing.T) {
	repoRoot, err := gitutil.FindGitRoot()
	if err != nil {
		t.Skipf("Skipping test: not in a git repository: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(repoRoot, ".github", "workflows", "issue-monster.md"))
	require.NoError(t, err, "Should read issue-monster workflow")

	text := string(content)
	assert.Contains(t, text, "latestAutoGeneratedIssueByTopic", "Workflow must retain the newest generated task per normalized topic")
	assert.Contains(t, text, "findSupersedingIssue", "Workflow must detect superseding generated tasks before assignment")
	assert.Contains(t, text, "superseded by newer auto-generated issue", "Workflow must exclude stale generated tasks with a newer duplicate")
	assert.Contains(t, text, "supersededIssues", "Workflow must emit compact staleness diagnostics")
	assert.Contains(t, text, "assign-to-agent:\n    max: 3", "Workflow must retain the bounded assignment cap")
}
