package filecheck

import (
	"go/ast"
	"go/parser"
	"go/token"
	"testing"

	"golang.org/x/tools/go/analysis"
)

func TestBuildGeneratedIndex(t *testing.T) {
	const generatedFilename = "generated.go"
	const regularFilename = "regular.go"

	fset := token.NewFileSet()
	generatedFile, err := parser.ParseFile(fset, generatedFilename, `// Code generated by test. DO NOT EDIT.
package p

func generated() {}
`, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseFile(generated) error = %v", err)
	}
	regularFile, err := parser.ParseFile(fset, regularFilename, `package p

func regular() {}
`, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseFile(regular) error = %v", err)
	}

	idx := BuildGeneratedIndex(&analysis.Pass{Fset: fset, Files: []*ast.File{generatedFile, regularFile}})
	if !IsGeneratedFile(generatedFilename, idx) {
		t.Fatalf("expected %q to be marked generated", generatedFilename)
	}
	if IsGeneratedFile(regularFilename, idx) {
		t.Fatalf("did not expect %q to be marked generated", regularFilename)
	}
}

func TestShouldSkipFilename(t *testing.T) {
	idx := GeneratedIndex{
		"generated.go": {},
	}

	if !ShouldSkipFilename("example_test.go", idx) {
		t.Fatalf("expected test file to be skipped")
	}
	if !ShouldSkipFilename("generated.go", idx) {
		t.Fatalf("expected generated file to be skipped")
	}
	if ShouldSkipFilename("regular.go", idx) {
		t.Fatalf("did not expect regular file to be skipped")
	}
}
