name: 'Update Issue Output'
description: 'Output for updating an existing issue. Note: The JavaScript validation ensures at least one of status, title, or body is provided.'
author: 'GitHub Next'

inputs:
  token:
    description: 'GitHub token for API authentication'
    required: true

runs:
  using: 'node20'
  main: 'index.js'

branding:
  icon: 'package'
  color: 'blue'
