# GitHub Copilot Agent Environment Configuration
# This file preinstalls tools and dependencies for the GitHub Copilot coding agent
# Documentation: https://docs.github.com/en/enterprise-cloud@latest/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

steps:
  - name: Set up Node.js
    uses: actions/setup-node@v5
    with:
      node-version: "24"
      cache: npm
      cache-dependency-path: pkg/workflow/js/package-lock.json

  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version-file: go.mod
      cache: true

  - name: npm ci
    run: npm ci
    working-directory: ./pkg/workflow/js

  - name: Build code
    run: make build
    continue-on-error: true
