#!/bin/bash
set +o histexpand

# check-workflow-drift.sh - Detect drift between workflow markdown sources and generated lock files
#
# Compiles all .github/workflows/*.md files and then checks whether the resulting
# .lock.yml files match what is already on disk.  Exits non-zero and prints a clear
# remediation message if any drift is detected.
#
# Usage:
#   check-workflow-drift.sh [<path-to-binary>]
#
# Arguments:
#   <path-to-binary>  Path to the gh-aw binary. Defaults to ./gh-aw.
#
# Exit codes:
#   0 - Lock files are up to date with their markdown sources
#   1 - Drift detected (lock files need to be regenerated)

set -euo pipefail

# Disable colors when not connected to a TTY, when NO_COLOR is set, or when
# TERM=dumb — this keeps output readable when captured into CI step summaries.
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ] && [ "${TERM:-}" != "dumb" ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    NC='\033[0m'
else
    RED=''
    GREEN=''
    YELLOW=''
    NC=''
fi

BINARY="${1:-./gh-aw}"

echo "Checking for workflow markdown/lock file drift..."
echo ""

# Compile all workflow markdown files, regenerating lock files in place.
# --validate:        enforce schema validation so compilation errors surface clearly
# --no-check-update: skip version-update check (CI-safe, avoids network calls)
# --purge:           remove orphaned .lock.yml files whose .md source was deleted
#
# The compiler skips writing a lock file when its content is already up to date,
# so running this on a clean checkout leaves the working tree unmodified.
if ! "$BINARY" compile --validate --no-check-update --purge 2>&1; then
    echo ""
    echo -e "${RED}ERROR${NC}: Workflow compilation failed — fix the errors above, then run:"
    echo ""
    echo "  make recompile"
    echo ""
    exit 1
fi

# Collect lock files that changed (modified or newly created by compilation).
# git diff --name-only: tracked files whose content changed
# git ls-files --others --exclude-standard: new untracked files (new lock files)
# git ls-files --deleted: tracked files removed by --purge
drift_modified=$(git diff --name-only -- '.github/workflows/*.lock.yml' 2>/dev/null || true)
drift_untracked=$(git ls-files --others --exclude-standard -- '.github/workflows/*.lock.yml' 2>/dev/null || true)
drift_deleted=$(git ls-files --deleted -- '.github/workflows/*.lock.yml' 2>/dev/null || true)

# Combine and de-duplicate
all_drift=$(printf '%s\n%s\n%s\n' "$drift_modified" "$drift_untracked" "$drift_deleted" \
    | grep -v '^$' | sort -u || true)

if [ -z "$all_drift" ]; then
    echo -e "${GREEN}✓ All workflow lock files are in sync with their markdown sources.${NC}"
    exit 0
fi

echo ""
echo -e "${RED}ERROR: Workflow lock files are out of sync with their markdown sources.${NC}"
echo ""
echo "The following lock files differ from what would be generated by compilation:"
echo ""
while IFS= read -r file; do
    echo "  $file"
done <<< "$all_drift"
echo ""
echo -e "${YELLOW}Fix:${NC} Run the following commands to regenerate the lock files and commit them:"
echo ""
echo "  make recompile"
echo "  git add .github/workflows/*.lock.yml"
echo "  git commit -m 'chore: regenerate workflow lock files'"
echo ""
echo "Lock files must always be committed together with their .md sources."
exit 1
