name: 'Update Pull Request Output'
description: 'Output for updating an existing pull request's title and/or body. Supports replace, append, or prepend operations for body updates. Note: The JavaScript validation ensures at least one of title or body is provided.'
author: 'GitHub Next'

inputs:
  token:
    description: 'GitHub token for API authentication'
    required: true

runs:
  using: 'node20'
  main: 'index.js'

branding:
  icon: 'package'
  color: 'blue'
