name: 'Create Issue Output'
description: 'Output for creating a GitHub issue'
author: 'GitHub Next'

inputs:
  token:
    description: 'GitHub token for API authentication'
    required: true

outputs:
  issue_number:
    description: 'Output parameter: issue_number'
  issue_url:
    description: 'Output parameter: issue_url'
  issues_to_assign_copilot:
    description: 'Output parameter: issues_to_assign_copilot'
  temporary_id_map:
    description: 'Output parameter: temporary_id_map'

runs:
  using: 'node20'
  main: 'index.js'

branding:
  icon: 'package'
  color: 'blue'
