name: Copilot
on:
  workflow_dispatch:
  push:
    branches:
      - copilot*
permissions: {}
jobs:
  copilot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install GitHub Copilot CLI
        run: npm install -g @github/copilot
      
      - name: Setup MCP Configuration
        run: |
          mkdir -p /home/runner/.copilot
          cat > /home/runner/.copilot/mcp-config.json << 'EOF'
          {
            "mcpServers": {
            }
          }
          EOF
          echo "-------START MCP CONFIG-----------"
          cat /home/runner/.copilot/mcp-config.json
          echo "-------END MCP CONFIG-----------"
          echo "HOME: $HOME"
          echo "GITHUB_COPILOT_CLI_MODE: $GITHUB_COPILOT_CLI_MODE"
      
      - name: Create prompt file
        env:
          GITHUB_AW_PROMPT: /tmp/aw-prompts/prompt.txt
        run: |
          mkdir -p $(dirname "$GITHUB_AW_PROMPT")
          cat > $GITHUB_AW_PROMPT << 'EOF'
          List tools defined in the current chat session (do not run commands, I am asking about tools defined in the LLM). Just the names in a table, nothing else.
          EOF      
      - name: Print prompt to step summary
        env:
          GITHUB_AW_PROMPT: /tmp/aw-prompts/prompt.txt
        run: |
          echo "## Generated Prompt" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```markdown' >> $GITHUB_STEP_SUMMARY
          cat $GITHUB_AW_PROMPT >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      
      - name: Execute GitHub Copilot CLI
        id: copilot_execution
        timeout-minutes: 5
        run: |
          INSTRUCTION=$(cat /tmp/aw-prompts/prompt.txt)
          copilot --prompt "$INSTRUCTION"
        env:
          XDG_CONFIG_HOME: /home/runner
          COPILOT_AGENT_RUNNER_TYPE: STANDALONE
          GITHUB_TOKEN: ${{ secrets.COPILOT_CLI_TOKEN }}
          GITHUB_STEP_SUMMARY: ${{ env.GITHUB_STEP_SUMMARY }}