name: Copilot
on:
  workflow_dispatch:
  push:
    branches:
      - copilot*
permissions: {}
jobs:
  copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install -g @github/copilot
      - run: |
          copilot --prompt "List tools defined in the current chat session (do not run commands, I am asking about tools defined in the LLM). Just the names in a table, nothing else."
        env:
          #XDG_CONFIG_HOME: /home/runner
          #COPILOT_AGENT_RUNNER_TYPE: STANDALONE
          GITHUB_TOKEN: ${{ secrets.COPILOT_CLI_TOKEN }}
          