on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/copilot.yml'
permissions: {}
jobs:
  copilot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install GitHub Copilot CLI
        run: npm install -g @github/copilot    
      - name: Setup MCP Configuration
        run: |
          mkdir -p /home/runner/.copilot
          cat > /home/runner/.copilot/mcp-config.json << 'EOF'
          {
            "mcpServers": {
              "tavily": {
                "type": "http",
                "url": "https://mcp.tavily.com/mcp/",
                "headers": {
                  "Authorization": "Bearer \${TAVILY_API_KEY}"
                },
                "tools": [
                  "*"
                ],
                "env": {
                  "TAVILY_API_KEY": "\${TAVILY_API_KEY}"
                }
              }
            }
          }
          EOF
          echo "-------START MCP CONFIG-----------"
          cat /home/runner/.copilot/mcp-config.json
          echo "-------END MCP CONFIG-----------"
          echo "HOME: $HOME"
          echo "GITHUB_COPILOT_CLI_MODE: $GITHUB_COPILOT_CLI_MODE"      
      - name: Execute GitHub Copilot CLI
        id: copilot_execution
        timeout-minutes: 5
        run: copilot --add-dir /tmp/ --log-level all --log-dir /home/runner/.copilot --prompt "If Tavily tools are not loaded, fail. Search for the latest trends in JavaScript frameworks. Provide a summary of your findings including popular frameworks, new developments, and emerging trends."
        env:
          XDG_CONFIG_HOME: /home/runner
          COPILOT_AGENT_RUNNER_TYPE: STANDALONE
          GITHUB_TOKEN: ${{ secrets.COPILOT_CLI_TOKEN }}
          GITHUB_STEP_SUMMARY: ${{ env.GITHUB_STEP_SUMMARY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      - name: Upload execution logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: copilot-logs
          path: /home/runner/.copilot/
          if-no-files-found: ignore
