on:
  workflow_dispatch:
  push:
    branches:
      - copilot*
permissions: 
  contents: read
  issues: read
jobs:
  copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install -g @github/copilot
      - run: echo "${{ secrets.GITHUB_TOKEN }}" > ~/.github_token
      - run: gh auth login --with-token < ~/.github_token
      - run: gh auth status
      - run: |
          copilot --log-level all --log-dir ./logs --prompt "List tools defined in the current chat session (do not run commands, I am asking about tools defined in the LLM). Just the names in a table, nothing else."
        env:
          GITHUB_TOKEN: ${{ secrets.COPILOT_CLI_TOKEN }}
      - run: echo "Listing all files in ./logs directory:"
      - run: ls -la ./logs
      - run: echo "Content of all files in ./logs directory:"
      - run: find ./logs -type f -exec echo "=== {} ===" \; -exec cat {} \;
