name: Copilot
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - copilot*
permissions: {}
jobs:
  copilot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install GitHub Copilot CLI
        run: npm install -g @github/copilot
      
      - name: Setup MCP Configuration
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.COPILOT_CLI_TOKEN }}
        run: |
          mkdir -p /home/runner/.copilot
          cat > /home/runner/.copilot/mcp-config.json << 'EOF'
          {
            "mcpServers": {
                "github": {
                  "type": "local",
                  "command": "docker",
                  "env": {
                    "GITHUB_PERSONAL_ACCESS_TOKEN": "GITHUB_PERSONAL_ACCESS_TOKEN"
                  },
                  "args": [
                    "run",
                    "-i",
                    "--rm",
                    "-e",
                    "GITHUB_PERSONAL_ACCESS_TOKEN",
                    "ghcr.io/github/github-mcp-server:sha-09deac4"
                  ],
                  "tools": ["*"]
                }
              }
            }
          }
          EOF
          echo "-------START MCP CONFIG-----------"
          cat /home/runner/.copilot/mcp-config.json
          echo "-------END MCP CONFIG-----------"
          echo "HOME: $HOME"
          echo "GITHUB_COPILOT_CLI_MODE: $GITHUB_COPILOT_CLI_MODE"
      
      - name: Create prompt file
        env:
          GITHUB_AW_PROMPT: /tmp/aw-prompts/prompt.txt
        run: |
          mkdir -p $(dirname "$GITHUB_AW_PROMPT")
          cat > $GITHUB_AW_PROMPT << 'EOF'
          List tools defined in the current chat session (do not run commands, I am asking about tools defined in the LLM). Just the names in a table, nothing else.
          EOF      
      - name: Print prompt to step summary
        env:
          GITHUB_AW_PROMPT: /tmp/aw-prompts/prompt.txt
        run: |
          echo "## Generated Prompt" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```markdown' >> $GITHUB_STEP_SUMMARY
          cat $GITHUB_AW_PROMPT >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      
      - name: Execute GitHub Copilot CLI
        id: copilot_execution
        timeout-minutes: 5
        run: |
          set -o pipefail
          
          INSTRUCTION=$(cat /tmp/aw-prompts/prompt.txt)
          
          # Run copilot CLI with log capture
          copilot --add-dir /tmp/ --log-level all --log-dir /tmp/.copilot/logs/ --prompt "$INSTRUCTION" 2>&1 | tee /tmp/agent-stdio.log
        env:
          XDG_CONFIG_HOME: /home/runner
          COPILOT_AGENT_RUNNER_TYPE: STANDALONE
          GITHUB_TOKEN: ${{ secrets.COPILOT_CLI_TOKEN }}
          GITHUB_STEP_SUMMARY: ${{ env.GITHUB_STEP_SUMMARY }}
      
      - name: Show execution logs
        if: always()
        run: |
          echo "=== Last 20 lines of Copilot execution log ==="
          tail -20 /tmp/agent-stdio.log || echo "No log content available"
      
      - name: Upload execution logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: copilot-logs
          path: |
            /tmp/agent-stdio.log
            /tmp/.copilot/logs/
          if-no-files-found: ignore
