name: Test Copilot GitHub Integration

on:
  workflow_dispatch:

permissions: {}

jobs:
  test-github-integration:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install GitHub Copilot CLI
        run: npm install -g @github/copilot
      
      - name: Setup MCP Configuration
        run: |
          mkdir -p /home/runner/.copilot
          cat > /home/runner/.copilot/mcp-config.json << 'EOF'
          {
            "mcpServers": {
            }
          }
          EOF
          echo "-------START MCP CONFIG-----------"
          cat /home/runner/.copilot/mcp-config.json
          echo "-------END MCP CONFIG-----------"
          echo "HOME: $HOME"
          echo "GITHUB_COPILOT_CLI_MODE: $GITHUB_COPILOT_CLI_MODE"
      
      - name: Create prompt file
        env:
          GH_AW_PROMPT: /tmp/gh-aw/aw-prompts/prompt.txt
        run: |
          mkdir -p $(dirname "$GH_AW_PROMPT")
          cat > $GH_AW_PROMPT << 'EOF'
          # Fetch Last Closed Pull Request
          Fetch the title of the last closed pull request in this repository.
          Then echo the title to the step summary.
          EOF
      
      - name: Print prompt to step summary
        env:
          GH_AW_PROMPT: /tmp/gh-aw/aw-prompts/prompt.txt
        run: |
          echo "## Generated Prompt" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```markdown' >> $GITHUB_STEP_SUMMARY
          cat $GH_AW_PROMPT >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      
      - name: Execute GitHub Copilot CLI
        id: copilot_execution
        timeout-minutes: 5
        run: |
          set -o pipefail
          
          INSTRUCTION=$(cat /tmp/gh-aw/aw-prompts/prompt.txt)
          
          # Run copilot CLI with log capture
          copilot --add-dir /tmp/gh-aw/ --log-level all --log-dir /tmp/gh-aw/.copilot/logs/ --prompt "$INSTRUCTION" 2>&1 | tee /tmp/gh-aw/agent-stdio.log
        env:
          XDG_CONFIG_HOME: /home/runner
          COPILOT_AGENT_RUNNER_TYPE: STANDALONE
          GITHUB_TOKEN: ${{ secrets.COPILOT_CLI_TOKEN }}
          GITHUB_STEP_SUMMARY: ${{ env.GITHUB_STEP_SUMMARY }}
      
      - name: Show execution logs
        if: always()
        run: |
          echo "=== Last 20 lines of Copilot execution log ==="
          tail -20 /tmp/gh-aw/agent-stdio.log || echo "No log content available"
      
      - name: Upload execution logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: copilot-logs
          path: |
            /tmp/gh-aw/agent-stdio.log
            /tmp/gh-aw/.copilot/logs/
          if-no-files-found: ignore
