---
name: Test gh pr list --author "@copilot"
on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test-author-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Test gh pr list with different author syntaxes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "======================================================"
          echo "Testing different gh pr list author filter syntaxes"
          echo "Repository: $REPO"
          echo "======================================================"
          echo ""
          
          # Test 1: @copilot
          echo "Test 1: gh pr list --author \"@copilot\""
          echo "------------------------------------------------------"
          gh pr list --repo "$REPO" \
            --author "@copilot" \
            --limit 10 \
            --state all \
            --json number,title,author \
            > /tmp/test1.json 2>&1 || echo "Failed with exit code $?"
          
          if [ -f /tmp/test1.json ]; then
            COUNT1=$(jq 'length' /tmp/test1.json 2>/dev/null || echo "0")
            echo "Found $COUNT1 PRs"
            echo "Sample:"
            jq '.[0:2] | .[] | {number, title, author: .author.login}' /tmp/test1.json 2>/dev/null || echo "No results"
          fi
          echo ""
          
          # Test 2: copilot (lowercase, no @)
          echo "Test 2: gh pr list --author \"copilot\""
          echo "------------------------------------------------------"
          gh pr list --repo "$REPO" \
            --author "copilot" \
            --limit 10 \
            --state all \
            --json number,title,author \
            > /tmp/test2.json 2>&1 || echo "Failed with exit code $?"
          
          if [ -f /tmp/test2.json ]; then
            COUNT2=$(jq 'length' /tmp/test2.json 2>/dev/null || echo "0")
            echo "Found $COUNT2 PRs"
            echo "Sample:"
            jq '.[0:2] | .[] | {number, title, author: .author.login}' /tmp/test2.json 2>/dev/null || echo "No results"
          fi
          echo ""
          
          # Test 3: Copilot (capitalized)
          echo "Test 3: gh pr list --author \"Copilot\""
          echo "------------------------------------------------------"
          gh pr list --repo "$REPO" \
            --author "Copilot" \
            --limit 10 \
            --state all \
            --json number,title,author \
            > /tmp/test3.json 2>&1 || echo "Failed with exit code $?"
          
          if [ -f /tmp/test3.json ]; then
            COUNT3=$(jq 'length' /tmp/test3.json 2>/dev/null || echo "0")
            echo "Found $COUNT3 PRs"
            echo "Sample:"
            jq '.[0:2] | .[] | {number, title, author: .author.login}' /tmp/test3.json 2>/dev/null || echo "No results"
          fi
          echo ""
          
          # Test 4: Full list + manual filter (baseline)
          echo "Test 4: gh pr list (all) + jq filter"
          echo "------------------------------------------------------"
          gh pr list --repo "$REPO" \
            --limit 100 \
            --state all \
            --json number,title,author \
            > /tmp/test4-raw.json 2>&1 || echo "Failed with exit code $?"
          
          if [ -f /tmp/test4-raw.json ]; then
            jq '[.[] | select(.author.login == "Copilot" or .author.id == 198982749)]' \
              /tmp/test4-raw.json > /tmp/test4.json 2>/dev/null || echo "jq filter failed"
            
            COUNT4=$(jq 'length' /tmp/test4.json 2>/dev/null || echo "0")
            echo "Found $COUNT4 PRs with author.login == \"Copilot\""
            echo "Sample:"
            jq '.[0:2] | .[] | {number, title, author: .author.login}' /tmp/test4.json 2>/dev/null || echo "No results"
          fi
          echo ""
          
          # Test 5: gh search prs (current workflow approach)
          echo "Test 5: gh search prs (current workflow method)"
          echo "------------------------------------------------------"
          DATE_30_DAYS_AGO=$(date -d '30 days ago' '+%Y-%m-%d' 2>/dev/null || date -v-30d '+%Y-%m-%d')
          
          gh search prs "repo:$REPO created:>=$DATE_30_DAYS_AGO" \
            --limit 100 \
            --json number,title,author \
            > /tmp/test5-raw.json 2>&1 || echo "Failed with exit code $?"
          
          if [ -f /tmp/test5-raw.json ]; then
            jq '[.[] | select(.author.login == "Copilot" or .author.id == 198982749)]' \
              /tmp/test5-raw.json > /tmp/test5.json 2>/dev/null || echo "jq filter failed"
            
            COUNT5=$(jq 'length' /tmp/test5.json 2>/dev/null || echo "0")
            echo "Found $COUNT5 PRs in last 30 days with author.login == \"Copilot\""
            echo "Sample:"
            jq '.[0:2] | .[] | {number, title, author: .author.login}' /tmp/test5.json 2>/dev/null || echo "No results"
          fi
          echo ""
          
          # Summary comparison
          echo "======================================================"
          echo "SUMMARY COMPARISON"
          echo "======================================================"
          echo "Test 1 (--author \"@copilot\"):        $COUNT1 PRs"
          echo "Test 2 (--author \"copilot\"):         $COUNT2 PRs"
          echo "Test 3 (--author \"Copilot\"):         $COUNT3 PRs"
          echo "Test 4 (full list + jq filter):      $COUNT4 PRs"
          echo "Test 5 (gh search prs + jq filter):  $COUNT5 PRs"
          echo ""
          
          # Compare results
          echo "======================================================"
          echo "DETAILED COMPARISON"
          echo "======================================================"
          
          if [ -f /tmp/test1.json ] && [ -f /tmp/test4.json ]; then
            echo "Comparing Test 1 vs Test 4 (baseline):"
            DIFF14=$(diff <(jq -r '.[].number' /tmp/test1.json | sort) <(jq -r '.[].number' /tmp/test4.json | head -10 | sort) 2>/dev/null || echo "Different")
            if [ -z "$DIFF14" ]; then
              echo "✅ Test 1 matches baseline (first 10 results)"
            else
              echo "❌ Test 1 differs from baseline"
              echo "$DIFF14"
            fi
          fi
          echo ""
          
          if [ -f /tmp/test3.json ] && [ -f /tmp/test4.json ]; then
            echo "Comparing Test 3 vs Test 4 (baseline):"
            DIFF34=$(diff <(jq -r '.[].number' /tmp/test3.json | sort) <(jq -r '.[].number' /tmp/test4.json | head -10 | sort) 2>/dev/null || echo "Different")
            if [ -z "$DIFF34" ]; then
              echo "✅ Test 3 matches baseline (first 10 results)"
            else
              echo "❌ Test 3 differs from baseline"
              echo "$DIFF34"
            fi
          fi
          echo ""
          
          # Final recommendation
          echo "======================================================"
          echo "RECOMMENDATION"
          echo "======================================================"
          if [ "$COUNT1" -gt 0 ] || [ "$COUNT3" -gt 0 ]; then
            echo "✅ gh pr list --author works for Copilot bot PRs"
            echo ""
            echo "Recommended syntax:"
            if [ "$COUNT1" -gt 0 ]; then
              echo "  gh pr list --author \"@copilot\""
            fi
            if [ "$COUNT3" -gt 0 ] && [ "$COUNT3" -ge "$COUNT1" ]; then
              echo "  gh pr list --author \"Copilot\""
            fi
          else
            echo "❌ gh pr list --author does not work for Copilot bot PRs"
            echo ""
            echo "Stick with current approach:"
            echo "  gh search prs + jq filtering"
          fi
